### ISSUE TITLE
Segfault with libevent 2.1.12 and no internet connection

### ISSUE THREAD

**Issue by olysonek** [transmission/transmission#1437]
When running Transmission built against libevent 2.1.12 and when there is no internet connection (or more precisely /etc/resolv.conf is empty), Transmission segfaults due to a NULL pointer dereference upon exiting.

You can reproduce the problem in openSUSE Tumbleweed where libevent 2.1.12 is used already. Alternatively, you can reproduce it simply by building Transmission against libevent 2.1.12 and then running the test suite - several tests segfault. Below you can see the stack trace of blocklist-test.

The problem is that `evdns_base_new` can return NULL, especially since the below libevent commit, but Transmission doesn't handle that.
https://github.com/libevent/libevent/commit/fc51bf2c5b686f623c9a2906ddad4042d5c3b39a

`libeventThreadFunc` calls `evdns_base_new`, which returns NULL and Transmission attempts to free it later on, which causes the NULL pointer dereference.

```
<mock-chroot> sh-5.0# gdb ./libtransmission/blocklist-test 
[snip]
(gdb) run
[snip]
Thread 2 "blocklist-test" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff7388700 (LWP 36)]
0x00007ffff7f02d31 in evdns_base_free (base=0x0, fail_requests=0) at evdns.c:4165
4165		EVDNS_LOCK(base);
(gdb) where
#0  0x00007ffff7f02d31 in evdns_base_free (base=0x0, fail_requests=0) at evdns.c:4165
#1  0x0000555555565c89 in sessionCloseImplFinish (session=0x5555555e91e0) at session.c:1995
#2  sessionCloseImplWaitForIdleUdp (foo=<optimized out>, bar=<optimized out>, vsession=0x5555555e91e0) at session.c:1986
#3  0x00007ffff7eef2f0 in event_process_active_single_queue (base=base@entry=0x7ffff0000ba0, activeq=0x7ffff0000ff0, max_to_process=max_to_process@entry=2147483647, 
    endtime=endtime@entry=0x0) at event.c:1691
#4  0x00007ffff7eefa97 in event_process_active (base=0x7ffff0000ba0) at event.c:1783
#5  event_base_loop (base=base@entry=0x7ffff0000ba0, flags=flags@entry=0) at event.c:2006
#6  0x00007ffff7eefd3b in event_base_dispatch (event_base=event_base@entry=0x7ffff0000ba0) at event.c:1817
#7  0x0000555555575f48 in libeventThreadFunc (veh=0x5555555e9810) at trevent.c:263
#8  0x0000555555564b9c in ThreadFunc (_t=0x5555555e9890) at platform.c:104
#9  0x00007ffff7b13432 in start_thread () from /lib64/libpthread.so.0
#10 0x00007ffff7a41913 in clone () from /lib64/libc.so.6
(gdb) list
4160	}
4161	
4162	void
4163	evdns_base_free(struct evdns_base *base, int fail_requests)
4164	{
4165		EVDNS_LOCK(base);
4166		evdns_base_free_and_unlock(base, fail_requests);
4167	}
4168	
4169	void
(gdb) print base
$1 = (struct evdns_base *) 0x0
(gdb) frame 1
#1  0x0000555555565c89 in sessionCloseImplFinish (session=0x5555555e91e0) at session.c:1995
1995	    evdns_base_free(session->evdns_base, 0);
(gdb) list
1990	{
1991	    event_free(session->saveTimer);
1992	    session->saveTimer = NULL;
1993	
1994	    /* we had to wait until UDP trackers were closed before closing these: */
1995	    evdns_base_free(session->evdns_base, 0);
1996	    session->evdns_base = NULL;
1997	    tr_tracker_udp_close(session);
1998	    tr_udpUninit(session);
1999	
(gdb) frame 2
#2  sessionCloseImplWaitForIdleUdp (foo=<optimized out>, bar=<optimized out>, vsession=0x5555555e91e0) at session.c:1986
1986	    sessionCloseImplFinish(session);
(gdb) list
1981	        tr_tracker_udp_upkeep(session);
1982	        tr_timerAdd(session->saveTimer, 0, 100000);
1983	        return;
1984	    }
1985	
1986	    sessionCloseImplFinish(session);
1987	}
1988	
1989	static void sessionCloseImplFinish(tr_session* session)
1990	{
(gdb) frame 3
#3  0x00007ffff7eef2f0 in event_process_active_single_queue (base=base@entry=0x7ffff0000ba0, activeq=0x7ffff0000ff0, max_to_process=max_to_process@entry=2147483647, 
    endtime=endtime@entry=0x0) at event.c:1691
1691				evcb_callback(ev->ev_fd, res, ev->ev_arg);
(gdb) list
1686				short res;
1687				EVUTIL_ASSERT(ev != NULL);
1688				evcb_callback = *ev->ev_callback;
1689				res = ev->ev_res;
1690				EVBASE_RELEASE_LOCK(base, th_base_lock);
1691				evcb_callback(ev->ev_fd, res, ev->ev_arg);
1692			}
1693			break;
1694			case EV_CLOSURE_CB_SELF: {
1695				void (*evcb_selfcb)(struct event_callback *, void *) = evcb->evcb_cb_union.evcb_selfcb;
(gdb) frame 4
#4  0x00007ffff7eefa97 in event_process_active (base=0x7ffff0000ba0) at event.c:1783
1783					c = event_process_active_single_queue(base, activeq,
(gdb) list
1778		for (i = 0; i < base->nactivequeues; ++i) {
1779			if (TAILQ_FIRST(&base->activequeues[i]) != NULL) {
1780				base->event_running_priority = i;
1781				activeq = &base->activequeues[i];
1782				if (i < limit_after_prio)
1783					c = event_process_active_single_queue(base, activeq,
1784					    INT_MAX, NULL);
1785				else
1786					c = event_process_active_single_queue(base, activeq,
1787					    maxcb, endtime);
(gdb) frame 5
#5  event_base_loop (base=base@entry=0x7ffff0000ba0, flags=flags@entry=0) at event.c:2006
2006				int n = event_process_active(base);
(gdb) list
2001			update_time_cache(base);
2002	
2003			timeout_process(base);
2004	
2005			if (N_ACTIVE_CALLBACKS(base)) {
2006				int n = event_process_active(base);
2007				if ((flags & EVLOOP_ONCE)
2008				    && N_ACTIVE_CALLBACKS(base) == 0
2009				    && n != 0)
2010					done = 1;
(gdb) frame 6
#6  0x00007ffff7eefd3b in event_base_dispatch (event_base=event_base@entry=0x7ffff0000ba0) at event.c:1817
1817		return (event_base_loop(event_base, 0));
(gdb) list
1812	}
1813	
1814	int
1815	event_base_dispatch(struct event_base *event_base)
1816	{
1817		return (event_base_loop(event_base, 0));
1818	}
1819	
1820	const char *
1821	event_base_get_method(const struct event_base *base)
(gdb) frame 7
#7  0x0000555555575f48 in libeventThreadFunc (veh=0x5555555e9810) at trevent.c:263
263	        event_base_dispatch(base);
(gdb) list
258	    event_set_log_callback(logFunc);
259	
260	    /* loop until all the events are done */
261	    while (!eh->die)
262	    {
263	        event_base_dispatch(base);
264	    }
265	
266	    /* shut down the thread */
267	    tr_lockFree(eh->lock);
(gdb) frame 8
#8  0x0000555555564b9c in ThreadFunc (_t=0x5555555e9890) at platform.c:104
104	    t->func(t->arg);
(gdb) list
99	    pthread_detach(pthread_self());
100	#endif
101	
102	    tr_thread* t = _t;
103	
104	    t->func(t->arg);
105	
106	    tr_free(t);
107	
108	#ifdef _WIN32
(gdb) frame 9
#9  0x00007ffff7b13432 in start_thread () from /lib64/libpthread.so.0
(gdb) frame 10
#10 0x00007ffff7a41913 in clone () from /lib64/libc.so.6
```

**Comment by ckerr** [comment]
Yep, your writeup is correct. Thanks for finding this!

**Comment by limburgher** [comment]
Any updates?

**Comment by mgorny** [comment]
Ping.
