### ISSUE TITLE
build failure: new web client (cd453764b)

### ISSUE THREAD

**Issue by reardonia** [transmission/transmission#1480]
Doesn't seem to build on Debian (tried stable, testing, and unstable)

excerpt from make:
```
warning " > eslint-plugin-sonarjs@0.5.0" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0".
warning " > stylelint-config-primer@9.2.1" has unmet peer dependency "@primer/css@*".
warning "stylelint-config-primer > stylelint-order@2.2.1" has incorrect peer dependency "stylelint@^9.10.1 || ^10.0.0".
Done in 50.94s.
yarn run v1.22.4
$ /home/XXX/bin/transmission.git/Release/web/node_modules/.bin/webpack --config /home/XXX/bin/transmission.git/web/webpack.config.js --context /home/XXX/bin/transmission.git/web
/home/XXX/bin/transmission.git/Release/web/node_modules/webpack-cli/bin/cli.js:93
[5/7] ⠐ cwebp-bin               throw err;
                                ^

Error: Cannot find module 'mini-css-extract-plugin'
Require stack:
- /home/XXX/bin/transmission.git/web/webpack.config.js
- /home/XXX/bin/transmission.git/Release/web/node_modules/webpack-cli/bin/utils/convert-argv.js
- /home/XXX/bin/transmission.git/Release/web/node_modules/webpack-cli/bin/cli.js
- /home/XXX/bin/transmission.git/Release/web/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (/home/XXX/bin/transmission.git/Release/web/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/XXX/bin/transmission.git/web/webpack.config.js:3:30)
    at Module._compile (/home/XXX/bin/transmission.git/Release/web/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (/home/XXX/bin/transmission.git/Release/web/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/home/XXX/bin/transmission.git/Release/web/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/home/XXX/bin/transmission.git/Release/web/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /home/XXX/bin/transmission.git/Release/web/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/XXX/bin/transmission.git/Release/web/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at /home/XXX/bin/transmission.git/Release/web/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/home/XXX/bin/transmission.git/Release/web/node_modules/yargs/yargs.js:576:18)
    at /home/XXX/bin/transmission.git/Release/web/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/XXX/bin/transmission.git/Release/web/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/XXX/bin/transmission.git/Release/web/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/XXX/bin/transmission.git/web/webpack.config.js',
    '/home/XXX/bin/transmission.git/Release/web/node_modules/webpack-cli/bin/utils/convert-argv.js',
    '/home/XXX/bin/transmission.git/Release/web/node_modules/webpack-cli/bin/cli.js',
    '/home/XXX/bin/transmission.git/Release/web/node_modules/webpack/bin/webpack.js'
  ]
}
error Command failed with exit code 1.
```

**Comment by ckerr** [comment]
@reardonia, can you paste the build commands you used that led up to this?

I'm interested in seeing all the steps so that I can try & reproduce the issue; but in particular, I'm interested in how you invoked cmake to generate the makefiles

**Comment by reardonia** [comment]
Build commands?  Just "cmake .." and "make", nothing fancy.

Note that I had to change "yarn" to "yarnpkg" in web/CMakeLists to get it building in Ubuntu.

**Comment by AndreyPavlenko** [comment]
I'm getting the same error on Ubuntu. Build commands:
cmake -DENABLE_WEB=ON ..
make -j6

`$ /XXX/transmission/build/web/node_modules/.bin/webpack --config /XXX/transmission/web/webpack.config.js --context /XXX/transmission/web
[webpack-cli] Failed to load '/XXX/transmission/web/webpack.config.js' config
[webpack-cli] Error: Cannot find module 'mini-css-extract-plugin'
Require stack:
- /XXX/transmission/web/webpack.config.js
- /XXX/transmission/build/web/node_modules/webpack-cli/lib/webpack-cli.js
- /XXX/transmission/build/web/node_modules/webpack-cli/lib/bootstrap.js
- /XXX/transmission/build/web/node_modules/webpack-cli/bin/cli.js
- /XXX/transmission/build/web/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (/XXX/transmission/build/web/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/XXX/transmission/web/webpack.config.js:3:30)
    at Module._compile (/XXX/transmission/build/web/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/XXX/transmission/web/webpack.config.js',
    '/XXX/transmission/build/web/node_modules/webpack-cli/lib/webpack-cli.js',
    '/XXX/transmission/build/web/node_modules/webpack-cli/lib/bootstrap.js',
    '/XXX/transmission/build/web/node_modules/webpack-cli/bin/cli.js',
    '/XXX/transmission/build/web/node_modules/webpack/bin/webpack.js'
  ]
}
`

**Comment by AndreyPavlenko** [comment]
I've resolved the issue with this fix: https://github.com/AndreyPavlenko/transmission/commit/cdc7bd2f15c89fdc58bed2208392dd857cd479d5

**Comment by nephaste** [comment]
same problem here cross compiling with MUSL ToolChain...
the fix seems to work.. i can build it now

but not yet merged into dev release ...
