### ISSUE TITLE
Constant segfaults using transmission as a client for local daemon

### ISSUE THREAD

**Issue by witcheslive** [transmission/transmission#1599]
I am getting nearly continual segfaults trying to use transmission as an interface for a local daemon. I do not have issues running without the daemon. I am mostly trying to manually add a ton of torrents from Deluge which was having its own problems and it's taking forever because I found that it only sometimes it kind of works if I verify the data locally in the window then wait for it to add. Sometimes. I can't really find much of a rhyme or reason to it other than it is USUALLY when adding torrents. It also segfaults just because sometimes.

I am running gentoo with 3.0 (r1) and transmission is compiled with appindicator, gtk, nls, and qt5 USE flags. Here's what I could get out of GDB:

```anna@eurekapyros ~ $ gdb /usr/bin/transmission-qt
GNU gdb (Gentoo 10.1 vanilla) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/transmission-qt...
(No debugging symbols found in /usr/bin/transmission-qt)
(gdb) run
Starting program: /usr/bin/transmission-qt 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff2f0f640 (LWP 20021)]
[New Thread 0x7ffff26ec640 (LWP 20022)]
[New Thread 0x7ffff1eeb640 (LWP 20023)]
[New Thread 0x7ffff0b89640 (LWP 20024)]
[New Thread 0x7fffe1b93640 (LWP 20025)]
libpng warning: iCCP: known incorrect sRGB profile
[New Thread 0x7fffe0f0c640 (LWP 20037)]
[New Thread 0x7fffd3fff640 (LWP 20038)]
[New Thread 0x7fffd37fe640 (LWP 20039)]
[New Thread 0x7fffd2ffd640 (LWP 20040)]
[New Thread 0x7fffd27fc640 (LWP 20041)]
[New Thread 0x7fffd1ffb640 (LWP 20042)]
[New Thread 0x7fffd17fa640 (LWP 20043)]
[New Thread 0x7fffd0ff9640 (LWP 20044)]
[Thread 0x7fffe1b93640 (LWP 20025) exited]
[Thread 0x7fffd3fff640 (LWP 20038) exited]
[Thread 0x7fffd17fa640 (LWP 20043) exited]
[Thread 0x7fffd1ffb640 (LWP 20042) exited]
[Thread 0x7fffd2ffd640 (LWP 20040) exited]
[Thread 0x7fffd37fe640 (LWP 20039) exited]
[Thread 0x7fffd27fc640 (LWP 20041) exited]
[Thread 0x7fffd0ff9640 (LWP 20044) exited]
[New Thread 0x7fffd0ff9640 (LWP 20157)]
[Thread 0x7fffd0ff9640 (LWP 20157) exited]

Thread 1 "transmission-qt" received signal SIGSEGV, Segmentation fault.
0x00007ffff6806779 in operator==(QString const&, QString const&) () from /usr/lib64/libQt5Core.so.5```

**Comment by witcheslive** [comment]
I am trying to get a better stack trace but unfortunately I do not do much work on desktop applications and simply git cloning the 3.0 release commit and using the `directory` command in gdb doesn't seem to be doing it, I'm assuming because it is breaking in the qt sources for some kind of bad string comparison instead of within the transmission code itself. If some guidance could be offered on how to do this properly it would be much appreciated, and I will provide a full stack trace.

**Comment by sandrotosi** [comment]
I think we're seeing the same SIGSEGV in Debian, but we got a complete traceback:

```
sep 07 20:43:54 angela kernel: transmission-qt[63169] segfault at 25 ip 00007fe0b62fa7a9 sp 00007ffd62fd4738 error 4 in libQt5Core.so.5.15.2[7fe0b623a000+2fe000]
sep 07 20:43:54 angela kernel: Code: 90 48 8b 02 48 8b 36 41 89 c9 48 8b 48 10 8b 56 04 44 8b 40 04 48 03 76 10 48 01 c1 e9 b0 fc ff ff 49 89 f0 48 8b 07 49 8b 10 <48> 63 70 04 48 63 4a 04 39 ce 75 4b 48 83 ec 08 48 8d 3d a0 51 24

gdb has this backtrace:

(gdb) bt
#0  0x00007ffff67697a9 in operator==(QString const&, QString const&) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#1  0x00007ffff76cf3e5 in QLabel::setText(QString const&) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#2  0x00005555555c302f in FreeSpaceLabel::<lambda(const RpcResponse&)>::operator() (__closure=0x7fffffffce00, r=...) at FreeSpaceLabel.cc:87
#3  RpcQueue::<lambda(const RpcResponseFuture&)>::operator() (r=..., this=0x7fffffffce00) at RpcQueue.h:98
#4  std::_Function_handler<QFuture<RpcResponse>(const QFuture<RpcResponse>&), RpcQueue::normalizeFunc(const Func&) [with Func = FreeSpaceLabel::onTimer()::<lambda(const RpcResponse&)>; typename std::enable_if<std::is_same<typename std::result_of<Func(const RpcResponse&)>::type, void>::value>::type* <anonymous> = 0; RpcQueue::QueuedFunction = std::function<QFuture<RpcResponse>(const QFuture<RpcResponse>&)>]::<lambda(const RpcResponseFuture&)> >::_M_invoke(const std::_Any_data &, const QFuture<RpcResponse> &) (__functor=..., __args#0=...)
    at /usr/include/c++/9/bits/std_function.h:286
#5  0x00005555555f3eb1 in std::function<QFuture<RpcResponse> (QFuture<RpcResponse> const&)>::operator()(QFuture<RpcResponse> const&) const (__args#0=..., this=0x7fffffffce00)
    at /usr/include/c++/9/bits/std_function.h:688
#6  RpcQueue::runNext (this=0x555555dcf590, response=...) at RpcQueue.cc:76
#7  0x00005555555f47c8 in RpcQueue::stepFinished (this=0x555555dcf590) at RpcQueue.cc:48
#8  0x00007ffff68fe5e0 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007ffff66f0df5 in QFutureWatcherBase::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff759b15f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff68c7fca in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff68caa01 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007ffff691fe93 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff5645e6b in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff5646118 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff56461cf in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff691f51f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007ffff68c698b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007ffff68cec00 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x0000555555590a61 in main (argc=<optimized out>, argv=0x7fffffffd628) at Application.cc:649
```

reported as https://bugs.debian.org/993907

**Comment by anarcat** [comment]
i'm the reporter on Debian's side and can still reproduce this. it doesn't *always* happen, strangely. e.g. now i downloaded a few things and it didn't do it on the first one, but reliably crashed on all subsequent ones. maybe it's because it doesn't start the later torrents because of the queue? in any case the torrents *do* get added, which is nice, I guess.

**Comment by anarcat** [comment]
> Ahhh the freespace label crash. This is fixed by [16ec15d](https://github.com/transmission/transmission/commit/16ec15d84be033cbc95ce8c768fe690bd461ad2f) from #1604

oh good catch thanks! :)
