### ISSUE TITLE
libtransmission thread blocks on startup

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#2711]
Kind of nasty. I'm not sure when this regression was introduced, but it looks like the libtransmission thread is blocking for a couple of seconds on startup while calling upnpDiscoverDevices. Make nonblocking / move to worker thread?
```
Thread 14 (Thread 0x7fffb2797640 (LWP 4177062) "transmission-qt"):
#0  0x00007ffff7032cdf in __GI___poll (fds=fds@entry=0x7fffb2794ac8, nfds=nfds@entry=1, timeout=timeout@entry=2000) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff722b923 in poll (__timeout=2000, __nfds=1, __fds=0x7fffb2794ac8) at /usr/include/x86_64-linux-gnu/bits/poll2.h:46
#2  receivedata (socket=socket@entry=47, data=data@entry=0x7fffb2794d20 "M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:service:WANIPConnection:1\r\nMAN: \"ssdp:discover\"\r\nMX: 2\r\n\r\n", length=length@entry=1536, timeout=timeout@entry=2000, scope_id=scope_id@entry=0x7fffb2794c50) at receivedata.c:50
#3  0x00007ffff722c993 in ssdpDiscoverDevices (deviceTypes=deviceTypes@entry=0x7ffff7231b60 <deviceList.1>, delay=delay@entry=2000, multicastif=multicastif@entry=0x55555593de30 <tr_address_to_string(tr_address const*)::buf> "0.0.0.0", localport=localport@entry=0, ipv6=0, ipv6@entry=-858572032, ttl=<optimized out>, ttl@entry=246 '\366', error=0x7fffb27953c0, searchalltypes=0) at minissdpc.c:881
#4  0x00007ffff7227a44 in upnpDiscoverDevices (deviceTypes=deviceTypes@entry=0x7ffff7231b60 <deviceList.1>, delay=2000, multicastif=0x55555593de30 <tr_address_to_string(tr_address const*)::buf> "0.0.0.0", minissdpdsock=<optimized out>, localport=0, ipv6=-858572032, ttl=<optimized out>, error=<optimized out>, searchalltypes=0) at miniupnpc.c:328
#5  0x00007ffff7227c40 in upnpDiscover (delay=<optimized out>, multicastif=<optimized out>, minissdpdsock=<optimized out>, localport=<optimized out>, ipv6=<optimized out>, ttl=<optimized out>, error=0x7fffb27953c0) at miniupnpc.c:359
#6  0x00005555557adc56 in tr_upnpDiscover(int, char const*) (msec=2000, bindaddr=0x55555593de30 <tr_address_to_string(tr_address const*)::buf> "0.0.0.0") at ../libtransmission/upnp.cc:84
#7  0x00005555557ad4e2 in tr_upnpPulse(tr_upnp*, unsigned short, bool, bool, char const*) (handle=0x7fffac117c60, port=55606, isEnabled=true, doPortCheck=false, bindaddr=0x55555593de30 <tr_address_to_string(tr_address const*)::buf> "0.0.0.0") at ../libtransmission/upnp.cc:221
#8  0x00005555557a1e7a in natPulse(tr_shared*, bool) (s=0x7fffac0027d0, do_check=false) at ../libtransmission/port-forwarding.cc:101
#9  0x00005555557a2061 in onTimer(int, short, void*) (vshared=0x7fffac0027d0) at ../libtransmission/port-forwarding.cc:160
#10 0x00007ffff75ce03f in event_process_active_single_queue (base=base@entry=0x7fffac000c30, activeq=0x7fffac001080, max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0) at event.c:1691
#11 0x00007ffff75ce8df in event_process_active (base=0x7fffac000c30) at event.c:1783
#12 event_base_loop (base=0x7fffac000c30, flags=4) at event.c:2006
#13 0x0000555555727218 in libeventThreadFunc(tr_event_handle*) (events=0x555555f97e60) at ../libtransmission/trevent.cc:214
#14 0x000055555572a245 in std::__invoke_impl<void, void (*)(tr_event_handle*), tr_event_handle*>(std::__invoke_other, void (*&&)(tr_event_handle*), tr_event_handle*&&) (__f=@0x555555f9d6c0: 0x555555727160 <libeventThreadFunc(tr_event_handle*)>, __args=@0x555555f9d6b8: 0x555555f97e60) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:61
#15 0x000055555572a192 in std::__invoke<void (*)(tr_event_handle*), tr_event_handle*>(void (*&&)(tr_event_handle*), tr_event_handle*&&) (__fn=@0x555555f9d6c0: 0x555555727160 <libeventThreadFunc(tr_event_handle*)>, __args=@0x555555f9d6b8: 0x555555f97e60) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:96
#16 0x000055555572a152 in std::thread::_Invoker<std::tuple<void (*)(tr_event_handle*), tr_event_handle*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) (this=0x555555f9d6b8) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_thread.h:253
#17 0x000055555572a105 in std::thread::_Invoker<std::tuple<void (*)(tr_event_handle*), tr_event_handle*> >::operator()() (this=0x555555f9d6b8) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_thread.h:260
#18 0x000055555572a039 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(tr_event_handle*), tr_event_handle*> > >::_M_run() (this=0x555555f9d6b0) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_thread.h:211
#19 0x00007ffff619d694 in std::execute_native_thread_routine(void*) (__p=0x555555f9d6b0) at ../../../../../src/libstdc++-v3/src/c++11/thread.cc:82
#20 0x00007ffff6faf927 in start_thread (arg=<optimized out>) at pthread_create.c:435
#21 0x00007ffff703f9e4 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:100
```

**Comment by ckerr** [comment]
Ugh, looks like this has been around for quite awhile
