### ISSUE TITLE
Building from head, using included third-party libraries: psl build step fails

### ISSUE THREAD

**Issue by jacobmetrick** [transmission/transmission#2729]
Hey all, building from head once again, seeing an error:

```
[ 15%] Performing build step for 'psl'
Traceback (most recent call last):
  File "/home/jacob/AUR/transmission-cli-git/src/transmission/build/third-party/psl/src/psl/src/psl-make-dafsa", line 692, in <module>
    sys.exit(main())
  File "/home/jacob/AUR/transmission-cli-git/src/transmission/build/third-party/psl/src/psl/src/psl-make-dafsa", line 685, in main
    with open(sys.argv[-2], 'r', **codecs) as infile, open(sys.argv[-1], 'wb') as outfile:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jacob/AUR/transmission-cli-git/src/transmission/build/third-party/psl/src/psl/list/public_suffix_list.dat'
make[5]: *** [CMakeFiles/suffixes_dafsa.h.dir/build.make:70: CMakeFiles/suffixes_dafsa.h] Error 1
make[4]: *** [CMakeFiles/Makefile2:85: CMakeFiles/suffixes_dafsa.h.dir/all] Error 2
make[3]: *** [Makefile:136: all] Error 2
make[2]: *** [CMakeFiles/psl.dir/build.make:86: third-party/psl/src/psl-stamp/psl-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:350: CMakeFiles/psl.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

I'm imagining this dependency got out of sync in some way, but I'm not sure how

**Comment by mikedld** [comment]
README.md was updated in the same PR where libpsl got added: you now need to update submodules **recursively** because libpsl has a submodule of its own.

**Comment by ckerr** [comment]
Closing this issue as I believe it is resolved by @mikedld's comment. @jacobmetrick if the problem persists please reopen / refile

**Comment by jacobmetrick** [comment]
Yep, this worked, thanks for the help.
