### ISSUE TITLE
Linux crash on head - malloc error

### ISSUE THREAD

**Issue by jacobmetrick** [transmission/transmission#2736]
Hey all,

Getting a crash/error with Transmission on Linux, on main/head. It works OK for about 15 minutes, then crashes. All I see in my logs are:
`malloc(): invalid size (unsorted)` before the crash.

Happy to try debugging in various ways as well.

**Comment by ckerr** [comment]
Hey, thanks for reporting this and for testing from `main`.

If you could get a backtrace so that we can see what malloc is failing, that would help to track it down

**Comment by jacobmetrick** [comment]
Is it supposed to have it by default, or should I have compiled with a particular flag enabled to have it show up?

**Comment by LaserEyess** [comment]
Compile with `-DCMAKE_BUILD_TYPE=DEBUG` and then use gdb to get a backtrace.

**Comment by jacobmetrick** [comment]
Ok, I was able to get the backtrace, but my suspicion is that I have not compiled the service correctly, or used gdb improperly such that the "No symbol table info available" is not showing the parts in transmission's code where the issue is occurring. In this backtrace, it was thread 3 that got the SIGABRT. Not sure how to get that data in there and understood by gdb, I would have thought compiling with `-DCMAKE_BUILD_TYPE=DEBUG` would have done it but maybe I missed something.

```
Thread 5 (Thread 0x7fedc08c2640 (LWP 1647189) "transmission-da"):
#0  0x00007fedc31f38ca in __futex_abstimed_wait_common64 () from target:/usr/lib/libpthread.so.0
No symbol table info available.
#1  0x00007fedc31ed270 in pthread_cond_wait@@GLIBC_2.3.2 () from target:/usr/lib/libpthread.so.0
No symbol table info available.
#2  0x00007fedc2c65f01 in __gthread_cond_wait (__mutex=<optimized out>, __cond=<optimized out>) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu/bits/gthr-default.h:865
No locals.
#3  std::__condvar::wait (__m=..., this=<optimized out>) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/std_mutex.h:155
        __e = <optimized out>
        __e = <optimized out>
#4  std::condition_variable::wait (this=<optimized out>, __lock=...) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/condition_variable.cc:41
No locals.
#5  0x00005577450d9d84 in ?? ()
No symbol table info available.
#6  0x00007fedc2c6c3c4 in std::execute_native_thread_routine (__p=0x7fedbc0287c0) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:82
        __t = <optimized out>
#7  0x00007fedc31e7259 in start_thread () from target:/usr/lib/libpthread.so.0
No symbol table info available.
#8  0x00007fedc29875e3 in clone () from target:/usr/lib/libc.so.6
No symbol table info available.

Thread 4 (Thread 0x7fedc10c3640 (LWP 1647188) "transmission-da"):
#0  0x00007fedc294fa95 in clock_nanosleep@GLIBC_2.2.5 () from target:/usr/lib/libc.so.6
No symbol table info available.
#1  0x00007fedc2954c77 in nanosleep () from target:/usr/lib/libc.so.6
No symbol table info available.
#2  0x00005577450cc51b in ?? ()
No symbol table info available.
#3  0x00005577450c6907 in ?? ()
No symbol table info available.
#4  0x00007fedc2c6c3c4 in std::execute_native_thread_routine (__p=0x7fedbc008e40) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:82
        __t = <optimized out>
#5  0x00007fedc31e7259 in start_thread () from target:/usr/lib/libpthread.so.0
No symbol table info available.
#6  0x00007fedc29875e3 in clone () from target:/usr/lib/libc.so.6
No symbol table info available.

Thread 3 (Thread 0x7fedc1968640 (LWP 1647187) "transmission-da"):
#0  0x00007fedc28c5d22 in raise () from target:/usr/lib/libc.so.6
No symbol table info available.
#1  0x00007fedc28af862 in abort () from target:/usr/lib/libc.so.6
No symbol table info available.
#2  0x00007fedc2907d28 in __libc_message () from target:/usr/lib/libc.so.6
No symbol table info available.
#3  0x00007fedc290f92a in malloc_printerr () from target:/usr/lib/libc.so.6
No symbol table info available.
#4  0x00007fedc2913334 in _int_malloc () from target:/usr/lib/libc.so.6
No symbol table info available.
#5  0x00007fedc29144e1 in malloc () from target:/usr/lib/libc.so.6
No symbol table info available.
#6  0x00007fedc32eb694 in ?? () from target:/usr/lib/libevent-2.1.so.7
No symbol table info available.
#7  0x00007fedc32ec323 in evbuffer_reserve_space () from target:/usr/lib/libevent-2.1.so.7
No symbol table info available.
#8  0x00005577451270a6 in ?? ()
No symbol table info available.
#9  0x00005577450d0d00 in ?? ()
No symbol table info available.
#10 0x0000557745126fc6 in ?? ()
No symbol table info available.
#11 0x00005577450d05c1 in ?? ()
No symbol table info available.
#12 0x0000557745112f0a in ?? ()
No symbol table info available.
#13 0x0000557745117f55 in ?? ()
No symbol table info available.
#14 0x00005577451149c9 in ?? ()
No symbol table info available.
#15 0x00007fedc3314a27 in ?? () from target:/usr/lib/libevent-2.1.so.7
No symbol table info available.
#16 0x00007fedc32f3da8 in bufferevent_run_readcb_ () from target:/usr/lib/libevent-2.1.so.7
No symbol table info available.
#17 0x00007fedc32f8e25 in ?? () from target:/usr/lib/libevent-2.1.so.7
No symbol table info available.
#18 0x00007fedc32ff16e in ?? () from target:/usr/lib/libevent-2.1.so.7
No symbol table info available.
#19 0x00007fedc32ffa7f in event_base_loop () from target:/usr/lib/libevent-2.1.so.7
No symbol table info available.
#20 0x00005577450ca5f6 in ?? ()
No symbol table info available.
#21 0x00007fedc2c6c3c4 in std::execute_native_thread_routine (__p=0x55774536fc10) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:82
        __t = <optimized out>
#22 0x00007fedc31e7259 in start_thread () from target:/usr/lib/libpthread.so.0
No symbol table info available.
#23 0x00007fedc29875e3 in clone () from target:/usr/lib/libc.so.6
No symbol table info available.

Thread 2 (Thread 0x7fedc2169640 (LWP 1647186) "transmission-da"):
#0  0x00007fedc31f079c in read () from target:/usr/lib/libpthread.so.0
No symbol table info available.
#1  0x00005577450944a0 in ?? ()
No symbol table info available.
#2  0x00007fedc31e7259 in start_thread () from target:/usr/lib/libpthread.so.0
No symbol table info available.
#3  0x00007fedc29875e3 in clone () from target:/usr/lib/libc.so.6
No symbol table info available.

Thread 1 (Thread 0x7fedc216db80 (LWP 1647185) "transmission-da"):
#0  0x00007fedc298792e in epoll_wait () from target:/usr/lib/libc.so.6
No symbol table info available.
#1  0x00007fedc330a9e6 in ?? () from target:/usr/lib/libevent-2.1.so.7
No symbol table info available.
#2  0x00007fedc32ff8c9 in event_base_loop () from target:/usr/lib/libevent-2.1.so.7
No symbol table info available.
#3  0x00005577450938a2 in ?? ()
No symbol table info available.
#4  0x0000557745094c8a in ?? ()
No symbol table info available.
#5  0x000055774509171f in ?? ()
No symbol table info available.
#6  0x00007fedc28b0b25 in __libc_start_main () from target:/usr/lib/libc.so.6
No symbol table info available.
#7  0x000055774509212e in ?? ()
No symbol table info available.
```

**Comment by ckerr** [comment]
in gdb,  you can tell it to stop being interrupted by sigpipe with this:

```
(gdb) handle SIGPIPE nostop noprint pass
```

**Comment by jacobmetrick** [comment]
On a newer version of transmission, was no longer able to reproduce, therefore closing.
