### ISSUE TITLE
on startup, system pings filesystem for torrent contents more than necessary

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#2750]
This isn't a major performance hit so the answer might be to leave it as-is, but I wanted to document it for when I have more time to consider.

On startup, we have to check the mtimes of all the files to see if anything needs to be re-verified before pieces get uploaded to peers:

```
#2  0x000000000044d104 in tr_torrent::findFile at ../libtransmission/torrent.cc:2605
#3  0x000000000044ea1f in tr_torrent::initCheckedPieces (this=0x7fffcc9216f0, checked=..., mtimes=0x7fffcc82b010) at ../libtransmission/torrent.cc:3139
#4  0x00000000004ffdcc in loadProgress (dict=0x7ffff6119cc8, tor=0x7fffcc9216f0) at ../libtransmission/resume.cc:574
#5  0x00000000004fe7c0 in loadFromFile (tor=0x7fffcc9216f0, fieldsToLoad=18446744073709551615, did_migrate_filename=0x7ffff611a07e) at ../libtransmission/resume.cc:773
#6  0x00000000004fdbeb in tr_resume::load (tor=0x7fffcc9216f0, fields_to_load=18446744073709551615, ctor=0x686440, did_rename_to_hash_only_name=0x7ffff611a07e) at ../libtransmission/resume.cc:881
#7  0x000000000044753d in torrentInit (tor=0x7fffcc9216f0, ctor=0x686440) at ../libtransmission/torrent.cc:729
#8  0x0000000000447093 in tr_torrentNew (ctor=0x686440, setme_duplicate_of=0x0) at ../libtransmission/torrent.cc:857
```

Then a short time later, `tr_torrentStart()` has its own checks to see if files in the torrent have disappeared since the last time the torrent was started:

```
#2  0x000000000044d104 in tr_torrent::findFile at ../libtransmission/torrent.cc:2605
#3  0x000000000044fcdf in hasAnyLocalData (tor=0x7fffca890110) at ../libtransmission/torrent.cc:608
#4  0x000000000044fbbd in setLocalErrorIfFilesDisappeared (tor=0x7fffca890110) at ../libtransmission/torrent.cc:619
#5  0x0000000000449bf6 in torrentStart (tor=0x7fffca890110, bypass_queue=false) at ../libtransmission/torrent.cc:1393
#6  0x0000000000449b3d in tr_torrentStart (tor=0x7fffca890110) at ../libtransmission/torrent.cc:1423
#7  0x0000000000447dc8 in torrentInit (tor=0x7fffca890110, ctor=0x686440) at ../libtransmission/torrent.cc:824
#8  0x0000000000447093 in tr_torrentNew (ctor=0x686440, setme_duplicate_of=0x0) at ../libtransmission/torrent.cc:857
```

The latter bails after finding any file, so this this filesystem access probably isn't a major performance hit. However it is an unnecessary one _in the case of startup_ when the files' mtimes have already been scanned by `tr_torrent::initCheckedPieces()`.

**Comment by timothyhutz** [comment]
I would like to try and take a stab at stopping the second check.
