### ISSUE TITLE
Transmission daemon freezes with 100% CPU reading .part file

### ISSUE THREAD

**Issue by dbeinder** [transmission/transmission#2795]
The daemon can get into an endless loop here: https://github.com/transmission/transmission/blob/0be920156bd89a9df1ae57375887aa156e69778b/libtransmission/inout.cc#L32-L46

The problem occurred in a torrent that has most files set to skip, and there are .part files that are not fully allocated. The skipped file would be 1GB, but the .part file is only 3MB. For some reason, transmission tries to read a piece 700MB into the file.
This happens here: https://github.com/transmission/transmission/blob/ce10a5314a8cf435d152bee089e1e2e4b2fb3285/libtransmission/file-posix.cc#L779
However, `pread()` simply returns `0` when reading past the end of the file. And so `readEntireBuf()` becomes an endless loop.

Stack trace:
```
#0  0x00007f63f7559e2f in pread64 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000056246da9063f in tr_sys_file_read_at (handle=handle@entry=39, buffer=buffer@entry=0x7f63c828489d, size=size@entry=16384, offset=offset@entry=821360891, bytes_read=bytes_read@entry=0x7f63f549d440, error=error@entry=0x7f63f549d3d0)
    at libtransmission/file-posix.cc:779
#2  0x000056246dadee27 in (anonymous namespace)::readEntireBuf (error=<optimized out>, buflen=16384, buf=0x7f63c828489d "\220p\271ޗX\205\336\302\300\060j[䨆\032u\275", file_offset=821360891, fd=<optimized out>)
    at libtransmission/inout.cc:38
#3  (anonymous namespace)::readOrWriteBytes (buflen=<optimized out>, buf=<optimized out>, file_offset=<optimized out>, file_index=308, io_mode=(anonymous namespace)::IoMode::Read, tor=<optimized out>, session=<optimized out>)
    at libtransmission/inout.cc:168
#4  (anonymous namespace)::readOrWritePiece (tor=0x7f63f01c74c0, io_mode=(anonymous namespace)::IoMode::Read, buf=<optimized out>, buflen=16384, loc=...) at libtransmission/inout.cc:221
#5  0x000056246dad9355 in tr_cacheReadBlock (cache=<optimized out>, torrent=0x7f63f01c74c0, loc=..., len=16384, setme=0x7f63c828489d "\220p\271ޗX\205\336\302\300\060j[䨆\032u\275") at libtransmission/cache.cc:353
#6  0x000056246daf2916 in fillOutputBuffer (now=1647634701, msgs=0x7f63f341f820) at libtransmission/block-info.h:140
#7  peerPulse (vmsgs=0x7f63f341f820) at libtransmission/peer-msgs.cc:2283
#8  0x000056246daed876 in pumpAllPeers (mgr=0x7f63f0002250) at libtransmission/peer-mgr.cc:2572
```

**Comment by dbeinder** [comment]
Ahh, already fixed by https://github.com/transmission/transmission/commit/ce10a5314a8cf435d152bee089e1e2e4b2fb3285
