### ISSUE TITLE
tr_bandwidth assertions are expensive

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#2830]
It's easy to peg the CPU to 100% when debugging assertions are turned on due to the cost of bitfield assertions. Every time we add to the bitfield, we re-count the entire bitfield to confirm that the true count is correct.

This won't be an issue for stable releases since assertions are disabled there, but it would still be nice to improve this situation for testers / nightly build users.

Example trace:

```txt
#0  0x000000000050ab80 in __gnu_cxx::operator!=<unsigned char const*, std::vector<unsigned char, std::allocator<unsigned char> > > (__lhs=0 '\000', __rhs=7 '\a') at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_iterator.h:907
#1  0x0000000000509793 in tr_bitfield::countFlags (this=0x7fff08351ba0) at ../libtransmission/bitfield.cc:59
#2  0x0000000000509ccd in tr_bitfield::isValid (this=0x7fff08351ba0) at ../libtransmission/bitfield.cc:163
#3  0x000000000050a143 in tr_bitfield::setTrueCount (this=0x7fff08351ba0, n=214972) at ../libtransmission/bitfield.cc:237
#4  0x000000000050a2a2 in tr_bitfield::incrementTrueCount (this=0x7fff08351ba0, inc=1) at ../libtransmission/bitfield.cc:250
#5  0x000000000050a7c0 in tr_bitfield::set (this=0x7fff08351ba0, nth=934896, value=true) at ../libtransmission/bitfield.cc:345
#6  0x0000000000510b30 in tr_completion::addBlock (this=0x7fff08351b90, block=934896) at ../libtransmission/completion.cc:154
#7  0x000000000047e597 in tr_torrentGotBlock (tor=0x7fff08351a20, block=934896) at ../libtransmission/torrent.cc:2638
#8  0x000000000053d2d6 in peerCallbackFunc (peer=0x7fff5b9fb910, e=0x7ffff6119770, vs=0x7fff08ae2d80) at ../libtransmission/peer-mgr.cc:843
#9  0x00000000005562b5 in tr_peerMsgsImpl::publish (this=0x7fff5b9fb910, e=...) at ../libtransmission/peer-msgs.cc:565
#10 0x0000000000556325 in tr_peerMsgsImpl::publishGotBlock (this=0x7fff5b9fb910, req=0x7fff5b9fe240) at ../libtransmission/peer-msgs.cc:439
#11 0x00000000005522c3 in clientGotBlock (msgs=0x7fff5b9fb910, data=0x7fff79c13dd0, req=0x7fff5b9fe240) at ../libtransmission/peer-msgs.cc:1910
#12 0x00000000005510fa in readBtPiece (msgs=0x7fff5b9fb910, inbuf=0x7fff5ba5f3d0, inlen=3000, setme_piece_bytes_read=0x7ffff6119a38) at ../libtransmission/peer-msgs.cc:1600
```

**Comment by ckerr** [comment]
```diff
diff --git a/libtransmission/bitfield.cc b/libtransmission/bitfield.cc
index 13102b200..f755561c8 100644
--- a/libtransmission/bitfield.cc
+++ b/libtransmission/bitfield.cc
@@ -345,18 +345,23 @@ void tr_bitfield::set(size_t nth, bool value)
     }
 
     /* Already tested that val != nth bit so just swap */
-    flags_[nth >> 3U] ^= 0x80 >> (nth & 7U);
+    auto& byte = flags_[nth >> 3U];
+    auto const old_byte_pop = doPopcount(byte);
+    byte ^= 0x80 >> (nth & 7U);
+    auto const new_byte_pop = doPopcount(byte);
 
-    /* Branch is needed for the assertions. Otherwise incrementing
-       (val ? 1 : -1) is better */
     if (value)
     {
-        incrementTrueCount(1);
+        ++true_count_;
+        TR_ASSERT(old_byte_pop + 1 == new_byte_pop);
     }
     else
     {
-        decrementTrueCount(1);
+        --true_count_;
+        TR_ASSERT(new_byte_pop + 1 == old_byte_pop);
     }
+    have_all_hint_ = true_count_ == bit_count_;
+    have_none_hint_ = true_count_ == 0;
 }
 
 /* Sets bit range [begin, end) to 1 */
