### ISSUE TITLE
Failed assertion in libtransmission/webseed.cc:139: n_tasks > 0

### ISSUE THREAD

**Issue by mikedld** [transmission/transmission#3899]
Tested on 32a14290470c71029aea1f44c472c157d2a056d7 with GTK client. Happens after adding and removing (while still in progress) a couple of times a torrent with webseeds (e.g. ArchLinux torrents are known for it).

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff5de357f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff5d94f02 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff5d7f472 in __GI_abort () at abort.c:79
#4  0x00005555557bb609 in tr_assert_report(std::basic_string_view<char, std::char_traits<char> >, int, std::basic_string_view<char, std::char_traits<char> >) (file=".../libtransmission/webseed.cc", line=139, message="n_tasks > 0") at .../libtransmission/tr-assert.cc:18
#5  0x00005555558c1f5a in (anonymous namespace)::ConnectionLimiter::taskFailed() (this=0x5555562bc510) at .../libtransmission/webseed.cc:139
#6  0x00005555558c1cdb in (anonymous namespace)::ConnectionLimiter::taskFinished(bool) (this=0x5555562bc510, success=false) at .../libtransmission/webseed.cc:96
#7  0x00005555558c3273 in (anonymous namespace)::onPartialDataFetched(tr_web::FetchResponse const&) (web_response=...) at .../libtransmission/webseed.cc:450
#8  0x00005555556725cd in std::__invoke_impl<void, void (*&)(tr_web::FetchResponse const&), tr_web::FetchResponse const&>(std::__invoke_other, void (*&)(tr_web::FetchResponse const&), tr_web::FetchResponse const&) (__f=@0x7fff9d280bb0: 0x5555558c320b <(anonymous namespace)::onPartialDataFetched(tr_web::FetchResponse const&)>) at /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include/g++-v12/bits/invoke.h:61
#9  0x000055555567223c in std::__invoke_r<void, void (*&)(tr_web::FetchResponse const&), tr_web::FetchResponse const&>(void (*&)(tr_web::FetchResponse const&), tr_web::FetchResponse const&) (__fn=@0x7fff9d280bb0: 0x5555558c320b <(anonymous namespace)::onPartialDataFetched(tr_web::FetchResponse const&)>) at /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include/g++-v12/bits/invoke.h:111
#10 0x0000555555671eab in std::_Function_handler<void (tr_web::FetchResponse const&), void (*)(tr_web::FetchResponse const&)>::_M_invoke(std::_Any_data const&, tr_web::FetchResponse const&) (__functor=..., __args#0=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include/g++-v12/bits/std_function.h:290
#11 0x0000555555775841 in std::function<void (tr_web::FetchResponse const&)>::operator()(tr_web::FetchResponse const&) const (this=0x7fff9d280bb0, __args#0=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include/g++-v12/bits/std_function.h:591
#12 0x000055555577d4ea in std::__invoke_impl<void, std::function<void (tr_web::FetchResponse const&)> const, tr_web::FetchResponse const>(std::__invoke_other, std::function<void (tr_web::FetchResponse const&)> const&&, tr_web::FetchResponse const&&) (__f=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include/g++-v12/bits/invoke.h:61
#13 0x0000555555779be2 in std::__invoke<std::function<void (tr_web::FetchResponse const&)> const, tr_web::FetchResponse const>(std::function<void (tr_web::FetchResponse const&)> const&&, tr_web::FetchResponse const&&) (__fn=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include/g++-v12/bits/invoke.h:96
#14 0x00005555557761c3 in std::__apply_impl<std::function<void (tr_web::FetchResponse const&)> const, std::tuple<tr_web::FetchResponse> const, 0ul>(std::function<void (tr_web::FetchResponse const&)> const&&, std::tuple<tr_web::FetchResponse> const&&, std::integer_sequence<unsigned long, 0ul>) (__f=..., __t=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include/g++-v12/tuple:1852
#15 0x0000555555776201 in std::apply<std::function<void (tr_web::FetchResponse const&)> const, std::tuple<tr_web::FetchResponse> const>(std::function<void (tr_web::FetchResponse const&)> const&&, std::tuple<tr_web::FetchResponse> const&&) (__f=..., __t=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include/g++-v12/tuple:1863
#16 0x000055555577617d in tr_runInEventThread<std::function<void (tr_web::FetchResponse const&)>, tr_web::FetchResponse>(tr_session*, std::function<void (tr_web::FetchResponse const&)>&&, tr_web::FetchResponse&&)::{lambda()#1}::operator()() const (__closure=0x7fff9d280bb0) at .../libtransmission/trevent.h:37
#17 0x00005555557811d2 in std::__invoke_impl<void, tr_runInEventThread<std::function<void (tr_web::FetchResponse const&)>, tr_web::FetchResponse>(tr_session*, std::function<void (tr_web::FetchResponse const&)>&&, tr_web::FetchResponse&&)::{lambda()#1}&>(std::__invoke_other, tr_runInEventThread<std::function<void (tr_web::FetchResponse const&)>, tr_web::FetchResponse>(tr_session*, std::function<void (tr_web::FetchResponse const&)>&&, tr_web::FetchResponse&&)::{lambda()#1}&) (__f=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include/g++-v12/bits/invoke.h:61
#18 0x000055555577f6c1 in std::__invoke_r<void, tr_runInEventThread<std::function<void (tr_web::FetchResponse const&)>, tr_web::FetchResponse>(tr_session*, std::function<void (tr_web::FetchResponse const&)>&&, tr_web::FetchResponse&&)::{lambda()#1}&>(tr_runInEventThread<std::function<void (tr_web::FetchResponse const&)>, tr_web::FetchResponse>(tr_session*, std::function<void (tr_web::FetchResponse const&)>&&, tr_web::FetchResponse&&)::{lambda()#1}&) (__fn=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include/g++-v12/bits/invoke.h:111
#19 0x000055555577d55f in std::_Function_handler<void (), tr_runInEventThread<std::function<void (tr_web::FetchResponse const&)>, tr_web::FetchResponse>(tr_session*, std::function<void (tr_web::FetchResponse const&)>&&, tr_web::FetchResponse&&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include/g++-v12/bits/std_function.h:290
#20 0x00005555557846ba in std::function<void ()>::operator()() const (this=0x7fff9d280820) at /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include/g++-v12/bits/std_function.h:591
#21 0x00005555557c595a in onWorkAvailable(int, short, void*) (vsession=0x555555e86ed0) at .../libtransmission/trevent.cc:177
#22 0x00007ffff65c1581 in event_process_active_single_queue () at /usr/lib64/libevent-2.1.so.7
#23 0x00007ffff65c21e7 in event_base_loop () at /usr/lib64/libevent-2.1.so.7
#24 0x00005555557c5a7f in libeventThreadFunc(tr_event_handle*) (events=0x555555bc5700) at .../libtransmission/trevent.cc:202
#25 0x00005555557c7bb4 in std::__invoke_impl<void, void (*)(tr_event_handle*), tr_event_handle*>(std::__invoke_other, void (*&&)(tr_event_handle*), tr_event_handle*&&) (__f=@0x555555e82860: 0x5555557c59d7 <libeventThreadFunc(tr_event_handle*)>) at /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include/g++-v12/bits/invoke.h:61
#26 0x00005555557c7b29 in std::__invoke<void (*)(tr_event_handle*), tr_event_handle*>(void (*&&)(tr_event_handle*), tr_event_handle*&&) (__fn=@0x555555e82860: 0x5555557c59d7 <libeventThreadFunc(tr_event_handle*)>) at /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include/g++-v12/bits/invoke.h:96
#27 0x00005555557c7a99 in std::thread::_Invoker<std::tuple<void (*)(tr_event_handle*), tr_event_handle*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) (this=0x555555e82858) at /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include/g++-v12/bits/std_thread.h:252
#28 0x00005555557c7a52 in std::thread::_Invoker<std::tuple<void (*)(tr_event_handle*), tr_event_handle*> >::operator()() (this=0x555555e82858) at /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include/g++-v12/bits/std_thread.h:259
#29 0x00005555557c7a36 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(tr_event_handle*), tr_event_handle*> > >::_M_run() (this=0x555555e82850) at /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include/g++-v12/bits/std_thread.h:210
#30 0x00007ffff60e00cf in std::execute_native_thread_routine(void*) (__p=0x555555e82850) at /var/tmp/portage/sys-devel/gcc-12.2.0/work/gcc-12.2.0/libstdc++-v3/src/c++11/thread.cc:82
#31 0x00007ffff5de1845 in start_thread (arg=<optimized out>) at pthread_create.c:442
#32 0x00007ffff5e610ec in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by ckerr** [comment]
I looked into this and haven't found the problem yet. It needs to get fixed, but it's not a blocker for another beta release.
