### ISSUE TITLE
Segfault in GTK4 - Source uncertain

### ISSUE THREAD

**Issue by Harm133** [transmission/transmission#3955]
### What is the issue?

I first saw this when adding a 2nd download to a session and the layout was auto-sorted when the 2nd torrent started downloading, not sure if related.
Haven't been able to replicate afterwards.

```
Thread 1 "transmission-gt" received signal SIGSEGV, Segmentation fault.
Gtk::TreeNodeChildren::begin (this=this@entry=0x7fffffffe080) at gtk/gtkmm/treeiter.cc:251
Downloading 0.01 MB source file /usr/src/debug/build/gtk/gtkmm/treeiter.cc
251         if(!gtk_tree_model_iter_children(model_->gobj(), iter.gobj(), &gobject_))                                                                                                      
(gdb) bt
#0  Gtk::TreeNodeChildren::begin() (this=this@entry=0x7fffffffe080) at gtk/gtkmm/treeiter.cc:251
#1  0x000055555569848c in Session::Impl::update() (this=0x555555e5cad0) at /home/harm/Source/transmission-self/src/gtk/Session.cc:1410
#2  0x00005555555e4e5c in Application::Impl::update_model_once() (this=0x5555559297c0) at /home/harm/Source/transmission-self/src/gtk/Application.cc:1357
#3  Application::Impl::update_model_loop() (this=0x5555559297c0) at /home/harm/Source/transmission-self/src/gtk/Application.cc:1392
#4  0x00007ffff6fc8a66 in std::__invoke_impl<bool, bool (*)(sigc::internal::slot_rep*), sigc::internal::slot_rep*&>(std::__invoke_other, bool (*&&)(sigc::internal::slot_rep*), sigc::internal::slot_rep*&) (__f=<optimized out>) at /usr/include/c++/12.2.0/bits/invoke.h:61
#5  std::__invoke<bool (*)(sigc::internal::slot_rep*), sigc::internal::slot_rep*&>(bool (*&&)(sigc::internal::slot_rep*), sigc::internal::slot_rep*&) (__fn=<optimized out>)
    at /usr/include/c++/12.2.0/bits/invoke.h:96
#6  std::invoke<bool (*)(sigc::internal::slot_rep*), sigc::internal::slot_rep*&>(bool (*&&)(sigc::internal::slot_rep*), sigc::internal::slot_rep*&) (__fn=<optimized out>)
    at /usr/include/c++/12.2.0/functional:110
#7  sigc::slot<bool ()>::operator()() const (this=<optimized out>) at /usr/include/sigc++-3.0/sigc++/functors/slot.h:223
#8  (anonymous namespace)::glibmm_source_callback(void*) (data=<optimized out>) at ../glibmm/glib/glibmm/main.cc:200
#9  0x00007ffff694b042 in g_timeout_dispatch (source=0x555555d97690, callback=<optimized out>, user_data=<optimized out>) at ../glib/glib/gmain.c:5007
#10 0x00007ffff694a81b in g_main_dispatch (context=0x55555597c1b0) at ../glib/glib/gmain.c:3444
#11 g_main_context_dispatch (context=0x55555597c1b0) at ../glib/glib/gmain.c:4162
#12 0x00007ffff69a0ec9 in g_main_context_iterate.constprop.0 (context=0x55555597c1b0, block=1, dispatch=1, self=<optimized out>) at ../glib/glib/gmain.c:4238
#13 0x00007ffff69490d2 in g_main_context_iteration (context=context@entry=0x55555597c1b0, may_block=may_block@entry=1) at ../glib/glib/gmain.c:4303
#14 0x00007ffff6b1003e in g_application_run (application=0x55555597b250, argc=<optimized out>, argv=0x7fffffffe6b8) at ../glib/gio/gapplication.c:2571
#15 0x00005555555dc585 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /home/harm/Source/transmission-self/src/gtk/main.cc:122
```

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.0-beta.1.dev (4b65c4fa28)

**Comment by GaryElshaw** [comment]
I had something similar recently, resolved by cleaning out my build folder and rebuild cleanly.

**Comment by mikedld** [comment]
I think this is the same as #3954, as it happens when GTK client handles torrent events, e.g. when a torrent gets added/completed. The callback is also basically the same.
