### ISSUE TITLE
crash in tau_announce_request::requestFinished() in nightly builds

### ISSUE THREAD

**Issue by belovachap** [transmission/transmission#4006]
### What is the issue?

I've been following the main branch and I recently rebuilt transmission-gtk and it crashes after starting up and running for a few seconds. The output in the terminal isn't very helpful:

```
chapman@chapman-Alienware-Aurora-Ryzen-Edition:~$ transmission-gtk 
*** stack smashing detected ***: terminated
Aborted (core dumped)
```

Let me know if there's other things I can procure to help debug. It was working as of a few days ago.

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

f0a0b855c6a475acc7cf79e690752511b9ca9916

**Comment by GaryElshaw** [comment]
Because everything is so movable right now, are you building afresh?

**Comment by mikedld** [comment]
Would be lovely to narrow it down with e.g. [git bisect](https://git-scm.com/docs/git-bisect). Also please confirm that nothing else changed in that time, maybe it's one of the new torrents that you've added that's causing this, or the setting that you've adjusted.

**Comment by belovachap** [comment]
I tried building the latest on my laptop and I don't hit the error. I'll have to wait until I'm back at my main computer in a couple of days to troubleshoot and bisect it. I'll be back :)

**Comment by ckerr** [comment]
Also if you're doing your own build from git, you probably have all the debug symbols available and can get a good backtrace. Try running this on the _built_ version, i.e. the version in the `build/` directory when you build with cmake

```
$ gdb ./build/gtk/transmission-gtk
(gdb) handle SIGPIPE nostop noprint pass
(gdb) r -f
... run until Transmission crashes...
(gdb) thread apply all bt full
```

**Comment by belovachap** [comment]
@ckerr thanks for the `gdb` idea and commands. Here's my terminal output running it in the debugger:

[transmission_gtk_backtrace.txt](https://github.com/transmission/transmission/files/9854708/transmission_gtk_backtrace.txt)

Now I'll try going back to an earlier version of the main branch and see if the error goes away.

**Comment by belovachap** [comment]
I've jumped back to f22ce40c72bb9831a139fa5304b3a1012caa9284 and transmission-gtk stays up and starts downloading and uploading like before. Maybe we can bisect to narrow in on the code that's unhappy!

**Comment by ckerr** [comment]
@belovachap I'm not able to reproduce this crash and am looking at your gdb report. It's great in pointing out where the crash is; but if it's frequently crashing for you and since you're building from source, then the fastest path forward may be for you to crash it again under a bigger microscope.

If you build with sanitizers enabled and then run without gdb, do you get any interesting crash report when the app dies?

Here are the CMake arguments I use when building with sanitizers:

```sh
$ echo $PWD
/path/to/transmission
$ rm -rf build
$ mkdir build
$ cd build
$ cmake -DCMAKE_C_COMPILER="gcc" -DCMAKE_CXX_COMPILER="g++" -DCMAKE_CXX_FLAGS="-gdwarf-4 -fno-omit-frame-pointer -fsanitize=address,pointer-compare,pointer-subtract,leak,undefined" -DCMAKE_C_FLAGS="-gdwarf-4 -fno-omit-frame-pointer -fsanitize=address,pointer-compare,pointer-subtract,leak,undefined" -DENABLE_QT=ON -DENABLE_CLI=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DRUN_CLANG_TIDY=ON -DCMAKE_BUILD_TYPE=Debug ..
$ make
```

**Comment by ckerr** [comment]
oh wait, I think I see it. I need to test with larger swarms.

**Comment by belovachap** [comment]
Here's what doing your cmake resulted in:

```
chapman@chapman-Alienware-Aurora-Ryzen-Edition:~/code/transmission$ ./build/gtk/transmission-gtk 
/home/chapman/code/transmission/build/third-party/utp/src/utp/utp_internal.cpp:2576:84: runtime error: member access within misaligned address 0x6190007f1dec for type 'struct UTPSocketKeyData', which requires 8 byte alignment
0x6190007f1dec: note: pointer points here
  ff ff ff ff 00 00 00 00  00 00 00 00 00 00 ff ff  b9 7d be 3b fa 1a 00 00  ff 5c 00 00 00 00 00 00
              ^ 
/home/chapman/code/transmission/build/third-party/utp/src/utp/utp_internal.cpp:3319:14: runtime error: member access within misaligned address 0x61e00010ac04 for type 'struct UTPSocketKeyData', which requires 8 byte alignment
0x61e00010ac04: note: pointer points here
  ff ff ff ff 00 00 00 00  00 00 00 00 00 00 ff ff  ba e9 6f dd c8 aa 17 00  c5 23 00 00 80 29 17 00
              ^ 
/home/chapman/code/transmission/build/third-party/utp/src/utp/utp_internal.cpp:2907:10: runtime error: member access within misaligned address 0x61e00010ac7c for type 'struct UTPSocketKeyData', which requires 8 byte alignment
0x61e00010ac7c: note: pointer points here
  21 00 00 00 00 00 00 00  00 00 00 00 00 00 ff ff  6b bd 0d e0 81 92 17 00  5d 77 00 00 00 34 17 00
              ^ 
/home/chapman/code/transmission/build/third-party/utp/src/utp/utp_internal.cpp:2866:28: runtime error: member access within misaligned address 0x61e00010a704 for type 'struct UTPSocketKeyData', which requires 8 byte alignment
0x61e00010a704: note: pointer points here
  ff ff ff ff 00 00 00 00  00 00 00 00 00 00 ff ff  5c 74 0e 06 d5 c8 15 00  65 1e 00 00 00 ba 15 00
              ^ 
/home/chapman/code/transmission/build/third-party/utp/src/utp/utp_internal.cpp:2877:15: runtime error: member access within misaligned address 0x61e00010a704 for type 'struct UTPSocketKeyData', which requires 8 byte alignment
0x61e00010a704: note: pointer points here
  ff ff ff ff 00 00 00 00  00 00 00 00 00 00 ff ff  5c 74 0e 06 d5 c8 15 00  65 1e 00 00 00 ba 15 00
              ^ 
/home/chapman/code/transmission/build/third-party/utp/src/utp/utp_internal.cpp:2872:28: runtime error: member access within misaligned address 0x6220000f3b54 for type 'struct UTPSocketKeyData', which requires 8 byte alignment
0x6220000f3b54: note: pointer points here
  ff ff ff ff 00 00 00 00  00 00 00 00 00 00 ff ff  59 8e 22 84 d5 c8 00 00  f9 e9 00 00 00 d5 17 00
              ^ 
[msg] Nameserver 127.0.0.53:53 has failed: request timed out.
[msg] All nameservers have failed
[msg] Nameserver 127.0.0.53:53 is back up
[msg] Nameserver 127.0.0.53:53 has failed: request timed out.
[msg] All nameservers have failed
[msg] Nameserver 127.0.0.53:53 is back up
=================================================================
==3056787==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7f4ba1d47b70 at pc 0x7f4bb121f2c3 bp 0x7f4ba1d47730 sp 0x7f4ba1d46ed8
WRITE of size 882 at 0x7f4ba1d47b70 thread T14
    #0 0x7f4bb121f2c2 in __interceptor_memcpy ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:827
    #1 0x5645501371b3 in evbuffer_copyout_from /home/chapman/code/transmission/build/third-party/event/src/event/buffer.c:1231
    #2 0x5645501367cb in evbuffer_remove /home/chapman/code/transmission/build/third-party/event/src/event/buffer.c:1174
    #3 0x56454fbdd215 in libtransmission::Buffer::toBuf(void*, unsigned long) /home/chapman/code/transmission/libtransmission/tr-buffer.h:196
    #4 0x56454fbe08e2 in tau_announce_request::onResponse(tau_action_t, libtransmission::Buffer&) (/home/chapman/code/transmission/build/gtk/transmission-gtk+0x5aea8e2)
    #5 0x56454fbec1a2 in tr_announcer_udp_impl::handleMessage(unsigned char const*, unsigned long) /home/chapman/code/transmission/libtransmission/announcer-udp.cc:744
    #6 0x56454faeb958 in event_callback /home/chapman/code/transmission/libtransmission/tr-udp.cc:218
    #7 0x56455018f0e3 in event_persist_closure /home/chapman/code/transmission/build/third-party/event/src/event/event.c:1623
    #8 0x56455018fdc9 in event_process_active_single_queue /home/chapman/code/transmission/build/third-party/event/src/event/event.c:1682
    #9 0x564550191f4e in event_process_active /home/chapman/code/transmission/build/third-party/event/src/event/event.c:1783
    #10 0x564550194540 in event_base_loop /home/chapman/code/transmission/build/third-party/event/src/event/event.c:2006
    #11 0x56454faf9cc6 in libeventThreadFunc /home/chapman/code/transmission/libtransmission/trevent.cc:202
    #12 0x56454fb02800 in void std::__invoke_impl<void, void (*)(tr_event_handle*), tr_event_handle*>(std::__invoke_other, void (*&&)(tr_event_handle*), tr_event_handle*&&) /usr/include/c++/11/bits/invoke.h:61
    #13 0x56454fb02626 in std::__invoke_result<void (*)(tr_event_handle*), tr_event_handle*>::type std::__invoke<void (*)(tr_event_handle*), tr_event_handle*>(void (*&&)(tr_event_handle*), tr_event_handle*&&) /usr/include/c++/11/bits/invoke.h:96
    #14 0x56454fb023bd in void std::thread::_Invoker<std::tuple<void (*)(tr_event_handle*), tr_event_handle*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) /usr/include/c++/11/bits/std_thread.h:253
    #15 0x56454fb02239 in std::thread::_Invoker<std::tuple<void (*)(tr_event_handle*), tr_event_handle*> >::operator()() /usr/include/c++/11/bits/std_thread.h:260
    #16 0x56454fb021ed in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(tr_event_handle*), tr_event_handle*> > >::_M_run() /usr/include/c++/11/bits/std_thread.h:211
    #17 0x7f4baf3a92b2  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xdc2b2)
    #18 0x7f4baf052b42 in start_thread nptl/pthread_create.c:442
    #19 0x7f4baf0e49ff  (/lib/x86_64-linux-gnu/libc.so.6+0x1269ff)

Address 0x7f4ba1d47b70 is located in stack of thread T14 at offset 768 in frame
    #0 0x56454fbe02b9 in tau_announce_request::onResponse(tau_action_t, libtransmission::Buffer&) (/home/chapman/code/transmission/build/gtk/transmission-gtk+0x5aea2b9)

  This frame has 4 object(s):
    [48, 49) '<unknown>'
    [64, 88) '<unknown>'
    [128, 160) 'errmsg' (line 236)
    [192, 768) 'contiguous' (line 229) <== Memory access at offset 768 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
Thread T14 created by T0 here:
    #0 0x7f4bb123d685 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:216
    #1 0x7f4baf3a9388 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/lib/x86_64-linux-gnu/libstdc++.so.6+0xdc388)
    #2 0x56454fafa3f6 in tr_eventInit(tr_session*) /home/chapman/code/transmission/libtransmission/trevent.cc:219
    #3 0x56454f8d6b54 in tr_sessionInit(char const*, bool, tr_variant*) /home/chapman/code/transmission/libtransmission/session.cc:622
    #4 0x56454f198d43 in Application::Impl::on_startup() /home/chapman/code/transmission/gtk/Application.cc:591
    #5 0x56454f197dd3 in Application::on_startup() /home/chapman/code/transmission/gtk/Application.cc:552
    #6 0x7f4baff8bfba in Gio::Application_Class::startup_callback(_GApplication*) (/lib/x86_64-linux-gnu/libgiomm-2.4.so.1+0xdbfba)

SUMMARY: AddressSanitizer: stack-buffer-overflow ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:827 in __interceptor_memcpy
Shadow bytes around the buggy address:
  0x0fe9f43a0f10: f1 f1 f1 f1 01 f2 00 00 00 f2 f2 f2 f2 f2 00 00
  0x0fe9f43a0f20: 00 00 f2 f2 f2 f2 00 00 00 00 00 00 00 00 00 00
  0x0fe9f43a0f30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe9f43a0f40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe9f43a0f50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0fe9f43a0f60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00[f3]f3
  0x0fe9f43a0f70: f3 f3 f3 f3 f3 f3 f3 f3 f3 f3 f3 f3 f3 f3 00 00
  0x0fe9f43a0f80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe9f43a0f90: 00 00 00 00 00 00 00 00 f1 f1 f1 f1 00 00 00 f2
  0x0fe9f43a0fa0: 00 00 00 f2 00 00 00 f2 00 00 f8 f2 00 00 f8 f2
  0x0fe9f43a0fb0: 00 00 f8 f2 00 00 f8 f2 00 00 f8 f2 00 00 00 f2
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==3056787==ABORTING
chapman@chapman-Alienware-Aurora-Ryzen-Edition:~/code/transmission$ 
```

**Comment by ckerr** [comment]
@belovachap I wish all crash reports were as well-sourced as this one. Thanks for the extra reports!

**Comment by belovachap** [comment]
https://en.wikipedia.org/wiki/Linus%27s_law

**Comment by belovachap** [comment]
![image](https://user-images.githubusercontent.com/396781/197646597-56756877-324a-44fc-a9f6-36da871120aa.png)
