### ISSUE TITLE
DNS query for udp tracker announcement should not block other transactions

### ISSUE THREAD

**Issue by InsaneKnight** [transmission/transmission#4153]
### What is the issue?

After e065565cd4a3e54707aca906b67ce5ec04555dce, tau_tracker_upkeep_ex() becomes synchronous on DNS query, and tr_announcer::upkeep() uses the same event_base of the whole tr_session. 
```
#0  0x00007facd811afef in __GI___poll (fds=fds@entry=0x7facd695c7d8, nfds=nfds@entry=1, timeout=4627) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007facd814d48d in send_dg (statp=0x7facd6968d78, buf=<optimized out>, buflen=<optimized out>, buf2=<optimized out>, buflen2=<optimized out>, ansp=<optimized out>, anssizp=<optimized out>, terrno=<optimized out>, ns=<optimized out>, v_circuit=<optimized out>, 
    gotsomewhere=<optimized out>, anscp=<optimized out>, ansp2=<optimized out>, anssizp2=<optimized out>, resplen2=<optimized out>, ansp2_malloced=<optimized out>) at ./resolv/res_send.c:994
#2  0x00007facd814e14b in __GI___res_context_send (ctx=ctx@entry=0x7fac268ed4a0, buf=buf@entry=0x7facd695ca30 "\255|\001", buflen=buflen@entry=35, buf2=buf2@entry=0x7facd695ca54 "\355z\001", buflen2=buflen2@entry=35, ans=<optimized out>, 
    ans@entry=0x7facd695d290 "\255|\201\203", anssiz=<optimized out>, ansp=<optimized out>, ansp2=<optimized out>, nansp2=<optimized out>, resplen2=<optimized out>, ansp2_malloced=<optimized out>) at ./resolv/res_send.c:373
#3  0x00007facd814b59c in __GI___res_context_query (ctx=ctx@entry=0x7fac268ed4a0, name=name@entry=0x7facd695e6b0 "benouworldtrip.fr", class=class@entry=1, type=type@entry=439963904, answer=answer@entry=0x7facd695d290 "\255|\201\203", anslen=anslen@entry=2048, 
    answerp=<optimized out>, answerp2=<optimized out>, nanswerp2=<optimized out>, resplen2=<optimized out>, answerp2_malloced=<optimized out>) at ./resolv/res_query.c:221
#4  0x00007facd814c1da in __res_context_querydomain (answerp2_malloced=0x7facd695d264, resplen2=0x7facd695d260, nanswerp2=0x7facd695d25c, answerp2=0x7facd695d270, answerp=0x7facd695d268, anslen=2048, answer=0x7facd695d290 "\255|\201\203", type=439963904, class=1, 
    domain=0x0, name=0x7facd695e6b0 "benouworldtrip.fr", ctx=0x7fac268ed4a0) at ./resolv/res_query.c:633
#5  __GI___res_context_search (ctx=ctx@entry=0x7fac268ed4a0, name=name@entry=0x7facd695e6b0 "benouworldtrip.fr", class=class@entry=1, type=type@entry=439963904, answer=answer@entry=0x7facd695d290 "\255|\201\203", anslen=anslen@entry=2048, answerp=<optimized out>, 
    answerp2=<optimized out>, nanswerp2=<optimized out>, resplen2=<optimized out>, answerp2_malloced=<optimized out>) at ./resolv/res_query.c:389
#6  0x00007facd8145769 in __GI__nss_dns_gethostbyname4_r (name=name@entry=0x7facd695e6b0 "benouworldtrip.fr", pat=pat@entry=0x7facd695dbb0, buffer=0x7facd695dd10 "\377\002", buflen=<optimized out>, errnop=0x7facd69671f0, herrnop=herrnop@entry=0x7facd6967254, 
    ttlp=<optimized out>) at nss_dns/dns-host.c:418
#7  0x00007facd8110626 in get_nss_addresses (res=0x7facd695dbb0, tmpbuf=0x7facd695dd00, req=<optimized out>, name=<optimized out>) at ../sysdeps/posix/getaddrinfo.c:637
#8  gaih_inet (tmpbuf=0x7facd695dd00, naddrs=<synthetic pointer>, pai=0x7facd695db80, req=<optimized out>, service=<optimized out>, name=<optimized out>) at ../sysdeps/posix/getaddrinfo.c:1170
#9  __GI_getaddrinfo (name=<optimized out>, service=<optimized out>, hints=<optimized out>, pai=<optimized out>) at ../sysdeps/posix/getaddrinfo.c:2391
#10 0x000055ba3dc0f332 in host2sockaddr (error=0x7fac2452e940, port=..., host="benouworldtrip.fr") at /home/user/git/transmission/third-party/fmt/include/fmt/core.h:892
#11 tau_tracker_upkeep_ex (tracker=0x7fac2452e900, timeout_reqs=<optimized out>) at /home/user/git/transmission/libtransmission/announcer-udp.cc:603
#12 0x000055ba3dc114fa in tr_announcer_udp_impl::scrape (this=<optimized out>, request=..., response_func=0x55ba3dc1ae60 <on_scrape_done(tr_scrape_response const*, void*)>, user_data=0x55ba3fcd0e30) at /home/user/git/transmission/libtransmission/announcer-udp.cc:694
#13 0x000055ba3dc17d58 in scrape_request_delegate (announcer=0x7facc8001770, callback=0x55ba3dc1ae60 <on_scrape_done(tr_scrape_response const*, void*)>, callback_data=<optimized out>, request=0x7facd69613f0)
    at /home/user/git/transmission/libtransmission/announcer.cc:1429
#14 multiscrape (announcer=0x7facc8001770, tiers=...) at /home/user/git/transmission/libtransmission/announcer.cc:1492
#15 0x000055ba3dc182f3 in scrapeAndAnnounceMore (announcer=0x7facc8001770) at /home/user/git/transmission/libtransmission/announcer.cc:1572
#16 0x000055ba3dc18850 in tr_announcer::upkeep (this=0x7facc8001770) at /home/user/git/transmission/libtransmission/announcer.cc:1606
#17 0x00007facd8a1e428 in ?? () from /lib/x86_64-linux-gnu/libevent-2.1.so.7
#18 0x00007facd8a1eb77 in event_base_loop () from /lib/x86_64-linux-gnu/libevent-2.1.so.7
#19 0x000055ba3dbdc6d2 in libeventThreadFunc (events=0x55ba3fd1c4b0) at /home/user/git/transmission/libtransmission/trevent.cc:202
#20 0x00007facd7ed44a3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#21 0x00007facd80a7fd4 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#22 0x00007facd81285ac in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```
As shown in the backtrace of transmission-daemon above, when the system DNS is poor and torrents in the tr_session are many, the for loop at the end of multiscrape() may block a quite long time, making transactions in the tr_session, and even remote management timeout.

I suggest, if tau_tracker_upkeep_ex() is made synchronous, tr_announcer::upkeep() had better be called in an event_base looping in another thread, in order to prevent it from blocking transactions in the tr_session.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

e065565cd4a3e54707aca906b67ce5ec04555dce

**Comment by ckerr** [comment]
I should probably revert #4094
