### ISSUE TITLE
Weird crash caused by unhandled std::__throw_bad_function_call()

### ISSUE THREAD

**Issue by dmantipov** [transmission/transmission#4299]
### What is the issue?

Any ideas on debugging this?
```
#0  0x0000ffff8acb6c18 in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x0000ffff8ac6ee00 in raise () from /lib64/libc.so.6
#2  0x0000ffff8ac5b284 in abort () from /lib64/libc.so.6
#3  0x0000ffff8af45444 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#4  0x0000ffff8af42bf0 in __cxxabiv1::__terminate(void (*)()) () from /lib64/libstdc++.so.6
#5  0x0000ffff8af42c74 in std::terminate() () from /lib64/libstdc++.so.6
#6  0x0000ffff8af42fc8 in __cxa_throw () from /lib64/libstdc++.so.6
#7  0x0000ffff8af3e3e0 in std::__throw_bad_function_call() () from /lib64/libstdc++.so.6
#8  0x00000000004fc9c8 in std::function<void (tr_announce_response const&)>::operator()(tr_announce_response const&) const (this=0xffff85f57e08, __args#0=...) at /usr/include/c++/12/bits/std_function.h:590
#9  0x000000000050e378 in tr_announcer_impl::announce(tr_announce_request const&, std::function<void (tr_announce_response const&)>)::{lambda(tr_announce_response const&)#1}::operator()(tr_announce_response const&) const (__closure=0xffff85f57e00, response=...)
    at libtransmission/announcer.cc:217
#10 0x000000000051950c in std::__invoke_impl<void, tr_announcer_impl::announce(tr_announce_request const&, std::function<void (tr_announce_response const&)>)::{lambda(tr_announce_response const&)#1}&, tr_announce_response const&>(std::__invoke_other, tr_announcer_impl::announce(tr_announce_request const&, std::function<void (tr_announce_response const&)>)::{lambda(tr_announce_response const&)#1}&, tr_announce_response const&) (__f=...)
    at /usr/include/c++/12/bits/invoke.h:61
#11 0x0000000000516210 in std::__invoke_r<void, tr_announcer_impl::announce(tr_announce_request const&, std::function<void (tr_announce_response const&)>)::{lambda(tr_announce_response const&)#1}&, tr_announce_response const&>(tr_announcer_impl::announce(tr_announce_request const&, std::function<void (tr_announce_response const&)>)::{lambda(tr_announce_response const&)#1}&, tr_announce_response const&) (__fn=...)
    at /usr/include/c++/12/bits/invoke.h:111
#12 0x0000000000512a84 in std::_Function_handler<void (tr_announce_response const&), tr_announcer_impl::announce(tr_announce_request const&, std::function<void (tr_announce_response const&)>)::{lambda(tr_announce_response const&)#1}>::_M_invoke(std::_Any_data const&, tr_announce_response const&) (__functor=..., __args#0=...)
    at /usr/include/c++/12/bits/std_function.h:290
#13 0x00000000004fc9e8 in std::function<void (tr_announce_response const&)>::operator()(tr_announce_response const&) const (this=0xffff8a18a600, __args#0=...) at /usr/include/c++/12/bits/std_function.h:591
#14 0x00000000004f98c8 in tau_announce_request::requestFinished (this=0xffff8a18a4f8)
    at libtransmission/announcer-udp.cc:204
#15 0x00000000004f9aa4 in tau_announce_request::onResponse (this=0xffff8a18a4f8, action=TAU_ACTION_ANNOUNCE, 
    buf=...) at libtransmission/announcer-udp.cc:231
#16 0x00000000004fbe58 in tr_announcer_udp_impl::handleMessage (this=0x20049160, msg=0xffff8a18b030 "", 
    msglen=26) at libtransmission/announcer-udp.cc:663
#17 0x00000000004c0d44 in event_callback (s=15, type=2, vsession=0x20029f10)
    at libtransmission/tr-udp.cc:210
#18 0x0000ffff8b7f3db4 in event_process_active_single_queue () from /lib64/libevent-2.1.so.7
#19 0x0000ffff8b7f5b48 in event_base_loop () from /lib64/libevent-2.1.so.7
#20 0x00000000005b1b2c in tr_session_thread_impl::sessionThreadFunc (this=0x2002b200, evbase=0x20029270)
    at libtransmission/session-thread.cc:244
#21 0x00000000005b3d2c in std::__invoke_impl<void, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*> (
    __f=@0x20028c58: (void (tr_session_thread_impl::*)(tr_session_thread_impl * const, event_base *)) 0x5b1a70 <tr_session_thread_impl::sessionThreadFunc(event_base*)>, __t=@0x20028c50: 0x2002b200)
    at /usr/include/c++/12/bits/invoke.h:74
#22 0x00000000005b3c30 in std::__invoke<void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*> (
    __fn=@0x20028c58: (void (tr_session_thread_impl::*)(tr_session_thread_impl * const, event_base *)) 0x5b1a70 <tr_session_thread_impl::sessionThreadFunc(event_base*)>) at /usr/include/c++/12/bits/invoke.h:96
#23 0x00000000005b3b5c in std::thread::_Invoker<std::tuple<void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*> >::_M_invoke<0ul, 1ul, 2ul> (this=0x20028c48)
    at /usr/include/c++/12/bits/std_thread.h:258
#24 0x00000000005b3b00 in std::thread::_Invoker<std::tuple<void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*> >::operator() (this=0x20028c48)
    at /usr/include/c++/12/bits/std_thread.h:265
#25 0x00000000005b3ae0 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*> > >::_M_run (this=0x20028c40)
    at /usr/include/c++/12/bits/std_thread.h:210
#26 0x0000ffff8af73230 in execute_native_thread_routine () from /lib64/libstdc++.so.6
#27 0x0000ffff8acb4fb8 in start_thread () from /lib64/libc.so.6
#28 0x0000ffff8ad2075c in thread_start () from /lib64/libc.so.6
```

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

trunk as of a0b562376913ddd6dffd87fe210976319d2fdf2f

**Comment by ckerr** [comment]
I think this is fixed by #4285, so I'm going to close this issue.  @dmantipov please reopen / refile if you're still seeing this. Thanks!
