### ISSUE TITLE
MemorySanitizer: use-of-uninitialized-value in std::char_traits<char>::length(char const*)

### ISSUE THREAD

**Issue by dmantipov** [transmission/transmission#4407]
### What is the issue?

Building:
```
cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr -DRUN_CLANG_TIDY=OFF -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_FLAGS='-O0 -g3 -fsanitize=memory' -DCMAKE_CXX_FLAGS='-O0 -g3 -fsanitize=memory' ...
```
Running:
```
$ ./daemon/transmission-daemon -f --log-level=info
Uninitialized bytes in __interceptor_strlen at offset 41 inside [0x703000000000, 42)
==22736==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x555cace9d5cc in std::char_traits<char>::length(char const*) /usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/char_traits.h:395:9
    #1 0x555cace9affc in std::basic_string_view<char, std::char_traits<char>>::basic_string_view(char const*) /usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/string_view:134:16
    #2 0x555cad02647e in getSettingsFilename(tr_strbuf<char, 4096ul>&, char const*, char const*) source/libtransmission/session.cc:381:22
    #3 0x555cad025f5f in tr_sessionLoadSettings(tr_variant*, char const*, char const*) source/libtransmission/session.cc:404:5
    #4 0x555cace92b74 in tr_daemon::init(int, char**, bool*, int*) source/daemon/daemon.cc:887:25
    #5 0x555cace9464c in main source/daemon/daemon.cc:939:17
    #6 0x7f049aabc50f in __libc_start_call_main (/lib64/libc.so.6+0x2750f) (BuildId: 765237b0355c030ff41d969eedcb87bfccb43595)
    #7 0x7f049aabc5c8 in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x275c8) (BuildId: 765237b0355c030ff41d969eedcb87bfccb43595)
    #8 0x555cacdfa0d4 in _start (objdir-x86_64-pc-linux-gnu/MemorySanitizer/daemon/transmission-daemon+0x17c0d4)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/char_traits.h:395:9 in std::char_traits<char>::length(char const*)
Exiting
```

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

trunk as of 76db72bc4b2443667f7cba2992d09a0bbe28875b

**Comment by ckerr** [comment]
I thought I had commented on this before but, looking over recent issues this morning, I don't see the reply...? I probably forgot to hit "comment". If so, sorry for the delay @dmantipov 

I looked through this a couple weeks ago and was  not able to figure it out: The usage in daemon.cc looks reasonable. My first guess was `std::string_view` since I've seen some bugs there in early versions of g++, but looks like this is happening on reasonably-modern RHEL12, so...? Probably not a std::string_view bug either.

@dmantipov was this a one-off or is it repeatable? I'd like to try and repeat this myself, but I regularly run daemon w/sanitizers and have not seen this myself.

**Comment by dmantipov** [comment]
It's definitely repeatable but I was unable to reproduce it when running against sanitized `libc++` and `libc++abi`. Most likely the sanitizer logic gets confused due to mixing of sanitized and non-sanitized code (which is possible unless _all_ code, including libraries, is sanitized).
