### ISSUE TITLE
Gtk-CRITICAL: gtk_css_node_insert_after: assertion 'previous_sibling == NULL || previous_sibling->parent == parent' failed

### ISSUE THREAD

**Issue by dmantipov** [transmission/transmission#4574]
### What is the issue?

Run under `gdb` with `export G_DEBUG=fatal-criticals`, left-click on a torrent (so select it) then press Shift key:
```
(transmission-gtk:195895): Gtk-CRITICAL **: 21:05:03.837: gtk_css_node_insert_after: assertion 'previous_sibling == NULL || previous_sibling->parent == parent' failed

Thread 1 "transmission-gt" received signal SIGTRAP, Trace/breakpoint trap.
g_logv (log_domain=0x7ffff7053086 "Gtk", log_level=G_LOG_LEVEL_CRITICAL, format=<optimized out>, args=<optimized out>) at ../glib/gmessages.c:1433
1433		  g_private_set (&g_log_depth, GUINT_TO_POINTER (depth));
```
Regular backtrace is:
```
#0  g_logv
    (log_domain=0x7ffff7053086 "Gtk", log_level=G_LOG_LEVEL_CRITICAL, format=<optimized out>, args=<optimized out>) at ../glib/gmessages.c:1433
#1  0x00007ffff6341133 in g_log
    (log_domain=<optimized out>, log_level=<optimized out>, format=<optimized out>)
    at ../glib/gmessages.c:1471
#2  0x00007ffff6ebbb83 in gtk_widget_reposition_after
     (widget=0x315c230 [GtkPopover], parent=0xcac470 [gtkmm__GtkTreeView], previous_sibling=<optimized out>)
    at ../gtk/gtkwidget.c:6015
#3  0x00007ffff6ea40d8 in gtk_tree_view_ensure_interactive_directory
    (tree_view=0xcac470 [gtkmm__GtkTreeView]) at ../gtk/gtktreeview.c:10001
#4  0x00007ffff6e97f0c in gtk_tree_view_forward_controller_key_pressed
    (key=0xc90230 [GtkEventControllerKey], keyval=65505, keycode=<optimized out>, state=<optimized out>, tree_view=0xcac470 [gtkmm__GtkTreeView]) at ../gtk/gtktreeview.c:5433
#5  0x00007ffff6cad9af in _gtk_marshal_BOOLEAN__UINT_UINT_FLAGSv
    (closure=<optimized out>, return_value=0x7fffffffd5c0, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0xb6d3e0) at gtk/gtkmarshalers.c:2256
#6  0x00007ffff6939554 in _g_closure_invoke_va
    (param_types=<optimized out>, n_params=<optimized out>, args=0x7fffffffd670, instance=<optimized out>, return_value=<optimized out>, closure=0xa955c0) at ../gobject/gclosure.c:895
#7  g_signal_emit_valist
    (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffd670) at ../gobject/gsignal.c:3456
#8  0x00007ffff6939633 in g_signal_emit
    (instance=instance@entry=0xc90230, signal_id=<optimized out>, detail=detail@entry=0)
    at ../gobject/gsignal.c:3606
#9  0x00007ffff6d3612d in gtk_event_controller_key_handle_event
    (controller=0xc90230 [GtkEventControllerKey], event=<optimized out>, x=<optimized out>, y=<optimized out>) at ../gtk/gtkeventcontrollerkey.c:121
#10 0x00007ffff6eb9392 in gtk_event_controller_handle_event
    (y=0, x=0, target=0xcac470 [gtkmm__GtkTreeView], event=0x2f22300 [GdkKeyEvent], controller=0xc90230 [GtkEventControllerKey]) at ../gtk/gtkeventcontroller.c:362
#11 gtk_widget_run_controllers
    (widget=widget@entry=0xcac470 [gtkmm__GtkTreeView], event=event@entry=0x2f22300 [GdkKeyEvent], target=target@entry=0xcac470 [gtkmm__GtkTreeView], x=0, y=0, phase=phase@entry=GTK_PHASE_BUBBLE)
    at ../gtk/gtkwidget.c:4523
#12 0x00007ffff6eb9679 in gtk_widget_event
    (target=0xcac470 [gtkmm__GtkTreeView], event=0x2f22300 [GdkKeyEvent], widget=0xcac470 [gtkmm__GtkTreeView]) at ../gtk/gtkwidget.c:4717
#13 gtk_widget_event
    (widget=0xcac470 [gtkmm__GtkTreeView], event=0x2f22300 [GdkKeyEvent], target=0xcac470 [gtkmm__GtkTreeView]) at ../gtk/gtkwidget.c:4693
#14 0x00007ffff704bc1e in gtk_propagate_event_internal.isra.0
    (widget=0xcac470 [gtkmm__GtkTreeView], event=0x2f22300 [GdkKeyEvent], topmost=<optimized out>)
    at ../gtk/gtkmain.c:1938
#15 0x00007ffff6dab1ed in gtk_main_do_event (event=0x2f22300 [GdkKeyEvent]) at ../gtk/gtkmain.c:1680
#16 0x00007ffff6ec780c in surface_event () at ../gtk/gtkwindow.c:4735
#17 0x00007ffff6f896b0 in _gdk_marshal_BOOLEAN__POINTERv
    (closure=<optimized out>, return_value=0x7fffffffdb90, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0xe0af10) at gdk/gdkmarshalers.c:302
#18 0x00007ffff6fb8ccb in gdk_surface_event_marshallerv
    (closure=0x2e314d0, return_value=0x7fffffffdb90, instance=0xbf70c0, args=0x7fffffffdc40, marshal_data=0x0, n_params=1, param_types=0xe0af10) at ../gdk/gdksurface.c:463
#19 0x00007ffff6939554 in _g_closure_invoke_va
    (param_types=<optimized out>, n_params=<optimized out>, args=0x7fffffffdc40, instance=<optimized out>, return_value=<optimized out>, closure=0x2e314d0) at ../gobject/gclosure.c:895
#20 g_signal_emit_valist
    (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffdc40) at ../gobject/gsignal.c:3456
#21 0x00007ffff6939633 in g_signal_emit
    (instance=instance@entry=0xbf70c0, signal_id=<optimized out>, detail=detail@entry=0)
    at ../gobject/gsignal.c:3606
#22 0x00007ffff704bcd3 in gdk_surface_handle_event.isra.0 (event=0x2f22300 [GdkKeyEvent])
    at ../gdk/gdksurface.c:2946
#23 0x00007ffff6fca6be in gdk_event_source_dispatch
    (base=<optimized out>, callback=<optimized out>, data=<optimized out>)
    at ../gdk/wayland/gdkeventsource.c:142
#24 0x00007ffff6338cbf in g_main_dispatch (context=0xa7de20) at ../glib/gmain.c:3444
#25 g_main_context_dispatch (context=0xa7de20) at ../glib/gmain.c:4162
#26 0x00007ffff638e598 in g_main_context_iterate.constprop.0
    (context=0xa7de20, block=1, dispatch=1, self=<optimized out>) at ../glib/gmain.c:4238
#27 0x00007ffff6335f40 in g_main_context_iteration
    (context=context@entry=0xa7de20, may_block=may_block@entry=1) at ../glib/gmain.c:4303
#28 0x00007ffff650394d in g_application_run
    (application=0xa7e250 [gtkmm__GtkApplication], argc=<optimized out>, argv=0x7fffffffe518)
    at ../gio/gapplication.c:2571
#29 0x00000000004fae44 in main(int, char**) (argc=1, argv=0x7fffffffe518)
    at /home/antipov/projects/transmission/source/gtk/main.cc:137
```
Observed on a recently updated Fedora 37, with all of the distribution-default `gtk4` etc. things.

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

trunk as of e4b480ecd45f79ff302a60ad2347a10e8dd7d4db

**Comment by ckerr** [comment]
CC @mikedld

**Comment by mathiascode** [comment]
This is a GTK issue with GtkTreeView:
https://gitlab.gnome.org/GNOME/gtk/-/issues/3561
https://gitlab.gnome.org/GNOME/gtk/-/issues/3585

**Comment by ckerr** [comment]
@mathiascode thanks for the links!

Closing this ticket since it's not fixable in Transmission's codebase; it has to be fixed upstream in GTK
