### ISSUE TITLE
transmission-daemon crashes with "Assertion '!(__hi < __lo)' failed"

### ISSUE THREAD

**Issue by maln0ir** [transmission/transmission#5069]
### What is the issue?

In short, I had this problem #5020 and I was pointed into this issue #5007, but workaround posted there (verify torrents) causes transmission-daemon to crash for (almost) every single torrent I have.

Details:
OS: Arch Linux
Package: transmission-cli 4.0.1-2
Transmission says:
```
transmission-cli 4.0.1 (e1c6e1be43)
```

Here is what journalctl says:

```
~ $ journalctl -l -u transmission.service | tail -n3
Feb 26 21:03:24 Nidhoggr transmission-daemon[145371]: /usr/include/c++/12.2.1/bits/stl_algo.h:3623: constexpr const _Tp& std::clamp(const _Tp&, const _Tp&, const _Tp&) [with _Tp = short unsigned int]: Assertion '!(__hi < __lo)' failed.
Feb 26 21:03:24 Nidhoggr systemd[1]: transmission.service: Main process exited, code=dumped, status=6/ABRT
Feb 26 21:03:24 Nidhoggr systemd[1]: transmission.service: Failed with result 'core-dump'.
```

This doesn't seem very useful, so I've rebuilt transmission with debug symbols. Here is what gdb says:

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = <optimized out>
        old_mask = {__val = {140200417485952}}
        ret = <optimized out>
#1  0x00007f8300ea0953 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
No locals.
#2  0x00007f8300e51ea8 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#3  0x00007f8300e3b53d in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x20, sa_sigaction = 0x20}, sa_mask = {__val = {94664692409128, 3623, 94664692409024, 0, 1677441804, 0, 
              72057598355534440, 140200642900064, 0, 0, 140200642900064, 1024, 140200625214408, 0, 0, 140200504780032}}, sa_flags = -299964672, sa_restorer = 0x0}
#4  0x00007f83010d30e2 in std::__glibcxx_assert_fail (file=file@entry=0x5618d75d2328 "/usr/include/c++/12.2.1/bits/stl_algo.h", line=line@entry=3623, 
    function=function@entry=0x5618d75d22c0 "constexpr const _Tp& std::clamp(const _Tp&, const _Tp&, const _Tp&) [with _Tp = short unsigned int]", 
    condition=condition@entry=0x5618d75d26ed "!(__hi < __lo)") at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/debug.cc:60
No locals.
#5  0x00005618d7517ea4 in std::clamp<unsigned short> (__val=<synthetic pointer>: <optimized out>, __lo=<synthetic pointer>: 5, __hi=<optimized out>)
    at /usr/include/c++/12.2.1/bits/stl_algo.h:3621
        __PRETTY_FUNCTION__ = <optimized out>
#6  std::clamp<unsigned short> (__hi=<optimized out>, __lo=<synthetic pointer>: 5, __val=<synthetic pointer>: <optimized out>)
    at /usr/include/c++/12.2.1/bits/stl_algo.h:3621
        __PRETTY_FUNCTION__ = <optimized out>
#7  (anonymous namespace)::rechoke_downloads_helpers::rechokeDownloads (s=0x7f82f414e480)
    at /usr/src/debug/transmission/transmission-4.0.1/libtransmission/peer-mgr.cc:1836
        MinInterestingPeers = 5
        peer_count = <optimized out>
        peers = std::vector of length 3, capacity 4 = {0x7f82f4136a90, 0x7f82f417e4f0, 0x7f82f417fc90}
        now = 1677441804
        max_peers = <optimized out>
        rechoke = std::vector of length 0, capacity 0
        salter = {pos = 0, buf = {_M_elems = '\000' <repeats 1023 times>}}
#8  0x00005618d7518178 in tr_peerMgr::rechokePulse (this=<optimized out>) at /usr/src/debug/transmission/transmission-4.0.1/libtransmission/peer-mgr.cc:2121
        swarm = 0x7f82f414e480
        tor = <optimized out>
        __for_range = <optimized out>
        __for_begin = <optimized out>
        __for_end = <optimized out>
        lock = {_M_device = 0x5618d9420680, _M_owns = true}
        now = 1677441804185
#9  0x00005618d751d570 in tr_peerMgr::rechokePulseMarshall (this=0x5618d93f3130) at /usr/src/debug/transmission/transmission-4.0.1/libtransmission/peer-mgr.cc:742
No locals.
#10 tr_peerMgr::tr_peerMgr(tr_session*)::{lambda()#2}::operator()() const (__closure=<optimized out>)
    at /usr/src/debug/transmission/transmission-4.0.1/libtransmission/peer-mgr.cc:693
        this = <optimized out>
        this = <optimized out>
#11 std::__invoke_impl<void, tr_peerMgr::tr_peerMgr(tr_session*)::{lambda()#2}&>(std::__invoke_other, tr_peerMgr::tr_peerMgr(tr_session*)::{lambda()#2}&) (__f=...)
    at /usr/include/c++/12.2.1/bits/invoke.h:61
No locals.
#12 std::__invoke_r<void, tr_peerMgr::tr_peerMgr(tr_session*)::{lambda()#2}&>(tr_peerMgr::tr_peerMgr(tr_session*)::{lambda()#2}&) (__fn=...)
    at /usr/include/c++/12.2.1/bits/invoke.h:111
No locals.
#13 std::_Function_handler<void (), tr_peerMgr::tr_peerMgr(tr_session*)::{lambda()#2}>::_M_invoke(std::_Any_data const&) (__functor=...)
    at /usr/include/c++/12.2.1/bits/std_function.h:290
No locals.
#14 0x00007f8301969c45 in event_persist_closure (ev=<optimized out>, base=0x5618d9421760) at /usr/src/debug/libevent/libevent-2.1.12-stable/event.c:1623
        evcb_callback = <optimized out>
        evcb_fd = <optimized out>
        evcb_res = 1
        evcb_arg = 0x5618d9422c50
        evcb_callback = <optimized out>
        evcb_fd = <optimized out>
        evcb_res = <optimized out>
        evcb_arg = <optimized out>
        __func__ = <optimized out>
        run_at = <optimized out>
        relative_to = <optimized out>
        delay = <optimized out>
        now = <optimized out>
        usec_mask = <optimized out>
#15 event_process_active_single_queue (base=base@entry=0x5618d9421760, activeq=0x5618d9421bb0, max_to_process=max_to_process@entry=2147483647, 
    endtime=endtime@entry=0x0) at /usr/src/debug/libevent/libevent-2.1.12-stable/event.c:1682
        ev = <optimized out>
        evcb_selfcb = <optimized out>
        evcb = <optimized out>
        count = 1
        __func__ = "event_process_active_single_queue"
#16 0x00007f830196b3af in event_process_active (base=0x5618d9421760) at /usr/src/debug/libevent/libevent-2.1.12-stable/event.c:1783
        activeq = <optimized out>
        i = 0
        c = 0
        tv = {tv_sec = 5363, tv_usec = 56220}
        maxcb = 2147483647
        endtime = 0x0
        limit_after_prio = 2147483647
        activeq = <optimized out>
        i = <optimized out>
        c = <optimized out>
        endtime = <optimized out>
        tv = <optimized out>
        maxcb = <optimized out>
        limit_after_prio = <optimized out>
        done = <optimized out>
#17 event_base_loop (base=0x5618d9421760, flags=4) at /usr/src/debug/libevent/libevent-2.1.12-stable/event.c:2006
        n = <optimized out>
        evsel = 0x7f8301996f80 <epollops>
        tv = {tv_sec = 0, tv_usec = 25995}
        tv_p = <optimized out>
        res = <optimized out>
        done = 0
        retval = 0
        __func__ = "event_base_loop"
#18 0x00005618d755c8dd in tr_session_thread_impl::sessionThreadFunc (this=0x5618d9421650, evbase=0x5618d9421760) at /usr/src/debug/transmission/transmission-4.0.1/libtransmission/session-thread.cc:245
        ToggleLooping = <optimized out>
#19 0x00007f83010d72c3 in std::execute_native_thread_routine (__p=0x5618d941fce0) at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/thread.cc:82
        __t = <optimized out>
#20 0x00007f8300e9ebb5 in start_thread (arg=<optimized out>) at pthread_create.c:444
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140200632772848, -8340450294010801948, -25944, 1, 140729465702288, 140200616853504, 8306542378889449700, 8306543675438993636}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#21 0x00007f8300f20d90 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
No locals.
```

Here are files I have in config dir that make it crash:

[7cb890a8886ae03491ba5f706a5b6655963b8f01.magnet.gz](https://github.com/transmission/transmission/files/10834668/7cb890a8886ae03491ba5f706a5b6655963b8f01.magnet.gz)
[7cb890a8886ae03491ba5f706a5b6655963b8f01.resume.gz](https://github.com/transmission/transmission/files/10834669/7cb890a8886ae03491ba5f706a5b6655963b8f01.resume.gz)
[7cb890a8886ae03491ba5f706a5b6655963b8f01.torrent.gz](https://github.com/transmission/transmission/files/10834670/7cb890a8886ae03491ba5f706a5b6655963b8f01.torrent.gz)

I hope you find this useful.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.1

**Comment by ckerr** [comment]
Huh, haven't seen that one before. Thanks for reporting it!

**Comment by maln0ir** [comment]
Updated backtrace with more details  (this is the same core dump, I just discovered I can print more :))

**Comment by ckerr** [comment]
@maln0ir thank you for taking the time to rebuild Transmission with debug symbols so that you could provide a backtrace. That is super helpful.
