### ISSUE TITLE
Segmentation fault (core dumped) 4.0.4

### ISSUE THREAD

**Issue by vitacell** [transmission/transmission#6349]
ArchLinux (updated yesterday)
-  transmission-gtk 4.0.4-1
Segmentation fault (core dumped), but nothing more, no info.

Hi guys, never had this before, and it never happened to me, but I have one torrent that I downloaded some months ago (already complete, and it was sharing), that one is inactive when I start transmission-gtk. When I "start" the torrent, (sometimes even it starts to sharing), after some seconds transmission crashes with segmentation fault.

The thing, I know how to trigger the crash, now, any instructions or guide how to see some debug or info for sharing it here?
Thanks.

**Comment by tearfur** [comment]
If you have a core dump, then could you please generate a backtrace for the crash?

Some reproduce steps will also be appreciated (please provide a public domain torrent if it only happens with specific torrents).

**Comment by vitacell** [comment]
> If you have a core dump, then could you please generate a backtrace for the crash?
> 
> Some reproduce steps will also be appreciated (please provide a public domain torrent if it only happens with specific torrents).

Hi, I have systemd's coredump, can it be somehow useful?
I also will share magnet link to the torrent here:
magnet:?xt=urn:btih:4e84d02de3f0278ad9dc531c82543f664e47dfc5&dn=%D0%A0%D0%BE%D0%BC%D0%B0%D0%BD%D0%BE%D0%B2&tr=http%3A%2F%2Fbt3.t-ru.org%2Fann%3Fmagnet

[debug-transmission-gtk.txt](https://github.com/transmission/transmission/files/13601765/debug-transmission-gtk.txt)
[sudo-coredump-info-2023-12-7-transmission-gtk.txt](https://github.com/transmission/transmission/files/13601767/sudo-coredump-info-2023-12-7-transmission-gtk.txt)

**Comment by tearfur** [comment]
After you input the command `coredumpctl debug` or something along those lines to get the output inside `sudo-coredump-info-2023-12-7-transmission-gtk.txt`, you can type in the prompt `bt full` (gdb) or `bt all` (lldb) to get the backtrace. See #6003 for an example of the output.

The information we are the most interested in is which line of the source code did the crash happen on.

Since you are using Arch, https://wiki.archlinux.org/title/Debugging/Getting_traces should have some good instructions in detail.

**Comment by vitacell** [comment]
> After you input the command `coredumpctl debug` or something along those lines to get the output inside `sudo-coredump-info-2023-12-7-transmission-gtk.txt`, you can type in the prompt `bt full` (gdb) or `bt all` (lldb) to get the backtrace. See #6003 for an example of the output.
> 
> The information we are the most interested in is which line of the source code did the crash happen on.
> 
> Since you are using Arch, https://wiki.archlinux.org/title/Debugging/Getting_traces should have some good instructions in detail.

Could this be somehow useful?
[gdb-transmission-gtk-latest.txt](https://github.com/transmission/transmission/files/13601922/gdb-transmission-gtk-latest.txt)
[gdb-transmission-gtk-backtrace.txt](https://github.com/transmission/transmission/files/13601923/gdb-transmission-gtk-backtrace.txt)

**Comment by vitacell** [comment]
> I think I know where this is happening and it's usually caused by non-utf8 folder/file names in the torrent, i.e. seems like UTF-8 sanitizing doesn't work well enough.
> 
> EDIT: Basically, the stack was already posted above. Getting it with GDB might show more info if it autoloads debug symbols, otherwise:
> 
> ```
>                 Stack trace of thread 5778:
>                 #0  0x00007fbfaf2d594a __wcscoll_l (libc.so.6 + 0xb794a)
>                 #1  0x00007fbfafb496b0 g_utf8_collate (libglib-2.0.so.0 + 0x956b0)
>                 #2  0x0000561e45ff6ad3 n/a (transmission-gtk + 0x113ad3)
>                 #3  0x0000561e45fee69a n/a (transmission-gtk + 0x10b69a)
>                 #4  0x0000561e45f7448a n/a (transmission-gtk + 0x9148a)
>                 #5  0x0000561e45f744f9 n/a (transmission-gtk + 0x914f9)
>                 #6  0x00007fbfb0b9f6a6 n/a (libglibmm-2.68.so.1 + 0x516a6)
>                 #7  0x00007fbfafb0f3ee n/a (libglib-2.0.so.0 + 0x5b3ee)
>                 #8  0x00007fbfafb0df69 n/a (libglib-2.0.so.0 + 0x59f69)
>                 #9  0x00007fbfafb6c327 n/a (libglib-2.0.so.0 + 0xb8327)
>                 #10 0x00007fbfafb0c162 g_main_context_iteration (libglib-2.0.so.0 + 0x58162)
>                 #11 0x00007fbfb0506b16 g_application_run (libgio-2.0.so.0 + 0xdfb16)
>                 #12 0x0000561e45f6541b n/a (transmission-gtk + 0x8241b)
>                 #13 0x00007fbfaf245cd0 n/a (libc.so.6 + 0x27cd0)
>                 #14 0x00007fbfaf245d8a __libc_start_main (libc.so.6 + 0x27d8a)
>                 #15 0x0000561e45f669b5 n/a (transmission-gtk + 0x839b5)
> ```
> 
> EDIT 2: For me it mostly happens when opening torrent properties dialog, which leads to file tree construction, and subsequent conversion of strings coming out of libtransmission into `Glib::ustring`s.

Yes, the torrent has all russian names.
Strange thing, that I have more torrents with all russian names, downloading and sharing, and nothing crashes.

**Comment by vitacell** [comment]
> @vitacell this is so close!
> 
> When you get that `(gdb)` prompt in those attachments, enter the command `bt` to get a backtrace of what the program was doing when it crashed.

Ok, thanks for guiding.
Here you have them. As I said, I have more russian naming torrents, and those run fine.
[gdb-transmission-gtk-when-click-on-torrent-properties.txt](https://github.com/transmission/transmission/files/13606250/gdb-transmission-gtk-when-click-on-torrent-properties.txt)
[gdb-transmission-gtk-when-click-start-torrent.txt](https://github.com/transmission/transmission/files/13606251/gdb-transmission-gtk-when-click-start-torrent.txt)

**Comment by vitacell** [comment]
> ```shell
> (gdb) bt
> #0  0x00007ffff5ed594a in wcscoll_l () at /usr/lib/libc.so.6
> #1  0x00007ffff69496b0 in g_utf8_collate () at /usr/lib/libglib-2.0.so.0
> #2  0x0000555555667ad3 in  ()
> #3  0x000055555565f69a in  ()
> #4  0x00005555555e548a in  ()
> #5  0x00005555555e54f9 in  ()
> #6  0x00007ffff739f6a6 in  () at /usr/lib/libglibmm-2.68.so.1
> #7  0x00007ffff690f3ee in  () at /usr/lib/libglib-2.0.so.0
> #8  0x00007ffff690df69 in  () at /usr/lib/libglib-2.0.so.0
> #9  0x00007ffff696c327 in  () at /usr/lib/libglib-2.0.so.0
> #10 0x00007ffff690c162 in g_main_context_iteration ()
>     at /usr/lib/libglib-2.0.so.0
> #11 0x00007ffff6506b16 in g_application_run () at /usr/lib/libgio-2.0.so.0
> #12 0x00005555555d641b in  ()
> #13 0x00007ffff5e45cd0 in  () at /usr/lib/libc.so.6
> #14 0x00007ffff5e45d8a in __libc_start_main () at /usr/lib/libc.so.6
> #15 0x00005555555d79b5 in  ()
> ```
> 
> @mikedld was right as usual 😸

So, it is the glib crap?
