### ISSUE TITLE
Build server is down

### ISSUE THREAD

**Issue by robd003** [transmission/transmission#7253]
### What is the issue?

The host build.transmissionbt.com isn't online

### Which application of Transmission?

None

### Which version of Transmission?

any

**Comment by robd003** [comment]
@ckerr would you be the person to notify for this?
@mikedld any chance you can get the build server back online?

**Comment by robd003** [comment]
...and it's back online

**Comment by robd003** [comment]
Unable to sync with GitHub:

```
Started on Nov 18, 2024, 5:15:09 PM
Started by event from 140.82.115.172 → 172.70.42.16 → 140.82.115.172 ⇒ https://build.transmissionbt.com:8080/github-webhook/ on Mon Nov 18 17:15:09 UTC 2024
Using strategy: Default
[poll] Last Built Revision: Revision 7e4b4f10a1f90885c0bebb168eedffe153f1cf53 (refs/remotes/origin/main)
The recommended git tool is: git
No credentials specified
 > git --version # timeout=10
 > git --version # timeout=10
 > git ls-remote -h https://github.com/transmission/transmission # timeout=10
FATAL: hudson.plugins.git.GitException: Error performing git command: git ls-remote -h https://github.com/transmission/transmission
java.io.IOException: error=0, Failed to exec spawn helper: pid: 3173698, exit value: 1
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
Caused: java.io.IOException: Cannot run program "git": error=0, Failed to exec spawn helper: pid: 3173698, exit value: 1
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at hudson.Proc$LocalProc.<init>(Proc.java:252)
	at hudson.Proc$LocalProc.<init>(Proc.java:221)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:994)
	at hudson.Launcher$ProcStarter.start(Launcher.java:506)
	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2839)
Caused: hudson.plugins.git.GitException: Error performing git command: git ls-remote -h https://github.com/transmission/transmission
	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2862)
	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2185)
	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2079)
	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2070)
	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.CliGitAPIImpl.getHeadRev(CliGitAPIImpl.java:3739)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.compareRemoteRevisionWithImpl(GitSCM.java:731)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.compareRemoteRevisionWith(GitSCM.java:690)
Caused: java.io.IOException
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.compareRemoteRevisionWith(GitSCM.java:692)
	at hudson.scm.SCM.compareRemoteRevisionWith(SCM.java:419)
	at hudson.scm.SCM.poll(SCM.java:436)
	at hudson.model.AbstractProject._poll(AbstractProject.java:1426)
	at hudson.model.AbstractProject.poll(AbstractProject.java:1332)
	at PluginClassLoader for github//com.cloudbees.jenkins.GitHubPushTrigger$1.runPolling(GitHubPushTrigger.java:125)
	at PluginClassLoader for github//com.cloudbees.jenkins.GitHubPushTrigger$1.run(GitHubPushTrigger.java:151)
	at hudson.util.SequentialExecutionQueue$QueueEntry.run(SequentialExecutionQueue.java:123)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Done. Took 6 ms
No changes
```

**Comment by robd003** [comment]
@Coeur do you have access to fix the build server?

**Comment by robd003** [comment]
Sorry for bothering you Antoine. I do wish you had more access in the project!

You're a great contributor on the macOS side of the project.
